### ISSUE TITLE
Transparent Approximation of Theory by Another

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#10]
If a certain solver does not support a given theory, but no other solver should be used, it can be interesting to approximate a theory with another one (mostly approximating BVs by LIA*UFs). This can be done (mostly) transparently in a wrapper layer, but poses problems for formula traversal (where the actual formula type is different than expected by the client).

The usefulness of this feature outside of CPAchecker is questionable, thus maybe it is better to not add it to JavaSMT.

**Comment by cheshire** [comment]
I'm tempted to say that this is too specific to CPAchecker.

**Comment by cheshire** [comment]
Closing for now, can be re-opened with a more concrete proposal.
