### ISSUE TITLE
Removing `isUnsatWithAssumptions`?

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#106]
Another refactoring question: we already have a method `unsatCoreOverAssumptions`, and it already returns either an unsat core, or reports that an underlying problem is actually satisfiable.
From my understanding, the assumptions are used exclusively to get an unsat core over them,
so the purpose of the method `isUnsatWithAssumptions` remains unclear.
It also makes `unsatCoreOverAssumptions` somewhat confusing, as it's not clear whether `isUnsatWithAssumptions` should be called beforehand, and what happens if the assumption set for two calls does not match.

**Comment by PhilippWendler** [comment]
Solving under assumptions is a meaningful and common operation for SMT solvers independently of unsat cores. It is used to ask series of queries over a common set of formulas, but where each query needs only a subset of the formulas.

**Comment by cheshire** [comment]
Right, it seems like I was confused by the fact that all references I have seen lately mention UNSAT cores.
