### ISSUE TITLE
Inconsistent API for using assumptions

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#108]
We offer two functions for using assumptions:

 - `isUnsatWithAssumptions`
 - `unsatCoreOverAssumptions`

Strangely, `ProverEnvironment` exposes both, but `InterpolatingProverEnvironment` only supports `isUnsatWithAssumptions`.
Neither is supported by the optimization prover (in our case, only Z3).

One option is to move both to `BasicProverEnvironment`, and to throw `UnsupportedOperationException` when the method is not supported (namely, in `OptimizationProverEnvironment`).
Any objections?

**Comment by kfriedberger** [comment]
Partially fixed:
- `isUnsatWithAssumption` is moved upwards.
- `getUnsatCoreOverAssumptions` remains in subclass, together with default `getUnsatCore`.

**Comment by kfriedberger** [comment]
Methods for unsat core also moved upwards.
