### ISSUE TITLE
Cloud-based Solver

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#11]
A solver package that implements the usual interface and delegates solving to a cloud-based webservice could be added (like in this [paper](https://dl.acm.org/citation.cfm?id=2393596.2393665)).

It is questionable whether this would be useful, given that many queries are faster than the typical internet latency, and supporting push/pop etc. would be difficult.

**Comment by cheshire** [comment]
Some people do this -- eg Isabelle exposes http://www.cs.miami.edu/~tptp/cgi-bin/SystemOnTPTP through the "sledgehammer" tactics.
However, their problems are usually much larger (I would think)

**Comment by cheshire** [comment]
TPTP has machines with Z3 and CVC4 installed; maybe it would be even possible to query their infrastructure.

**Comment by cheshire** [comment]
Wow, there is even a translator to TPTP format from SMT-LIB! https://bitbucket.org/peba123/smttotptp
Thus all we need to do is to dump a query in SMT-LIB and perform a query to the cloud solver.

**Comment by cheshire** [comment]
We would need to construct formulas though, as currently we are relying on solvers datastructures entirely.

**Comment by PhilippWendler** [comment]
Instead of our own formula representation, we could also use for example SmtInterpol for this task.

**Comment by dbeyer** [comment]
But will the TPTP people let us send many queries and produce significant load?
It looks like a web interface just for humans, not for machines.

**Comment by cheshire** [comment]
Doesn't look like this is coming anytime soon :P
