### ISSUE TITLE
Use list of values defined in SMTInterpol model

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#111]
After https://github.com/ultimate-pa/smtinterpol/issues/26, a method `Model.getDefinedFunctions()` was added to SMTInterpol's `Model` in https://github.com/ultimate-pa/smtinterpol/commit/4c543a594fcec0b5219112527af3a5981e75051c. We should make use of this.

**Comment by kfriedberger** [comment]
see 61248c44193b104591d6fe430e014ae64b5a6837 , to be tested extensively.

**Comment by PhilippWendler** [comment]
What is the status of this? The branch exists for more than half a year.

**Comment by kfriedberger** [comment]
Changes from branch were reintegrated in 029f8edf3097b012e6b2a20709306a08eeb39d62.
Should be working now.
