### ISSUE TITLE
Adjust to new interrupt handling of Z3

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#116]
https://github.com/Z3Prover/z3/commit/7a977f0106fe0ae07c90d1566a8a75e2d430f2f9 seems to have changed the handling of interrupts of Z3. It is not clear to me whether Z3 now still returns `canceled` or `interrupted` as error message when we interrupt it, so we need to test this and adjust our error handling accordingly.

**Comment by PhilippWendler** [comment]
Was this done now that Z3 was updated?

**Comment by kfriedberger** [comment]
For several cases, the interrupt behaviour of Z3 did not change.
For optimizazion (min/max) there seems to be a difference, which will be adapted soon.

**Comment by kfriedberger** [comment]
Should be fixed with 764addf53939711fb1e98aadc15463083c726821.

**Comment by PhilippWendler** [comment]
Is there still something left to do?

**Comment by kfriedberger** [comment]
I did not notice any problems since then, so we can close this issue.
