### ISSUE TITLE
Provide Windows binary for MathSAT

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#117]
MathSAT has Windows binaries on their [website](http://mathsat.fbk.eu/download.html). The archive contains a script that shows how to compile their Java bindings. We could adapt this script to compile our own Java bindings, which should work similarly. Then we could use AppVeyor to regularly build binaries for MathSAT and distribute them via our Ivy repository. It is possible to extract result files ("artifacts") from AppVeyor builds. or we could even commit them to our Ivy repository directly from within the build.

**Comment by kfriedberger** [comment]
Solved with #202.
