### ISSUE TITLE
Use reentrant version of MathSAT

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#118]
Since a few versions, the MathSAT developers provide a reentrant version in addition to the standard version. This version allows he same kind of concurrency as [the other solvers](https://github.com/sosy-lab/java-smt#multithreading-support): separate contexts can be used in parallel.

The MathSAT developers said that they do not know about the performance difference between these two versions, but that the linear-arithmetic solver would suffer most. So I did a comparison using CPAchecker with a configuration for predicate abstraction and linear arithmetic ([results](http://students.fim.uni-passau.de/~wendler/results/2017-09%20MathSAT5-reentrant/predicateAnalysis-linear.table.html)), and there was no noticeable difference. The same is true for a [comparison using bitprecise arithmetic](http://students.fim.uni-passau.de/~wendler/results/2017-09%20MathSAT5-reentrant/predicateAnalysis.table.html). MathSAT was used in version 5.4.1.

So I would like to suggest to bundle the reentrant version of MathSAT5 with JavaSMT. Alternatively, we could provide both versions, but it does not seem to be worth the effort.

**Comment by PhilippWendler** [comment]
@cheshire @kfriedberger 
Any thoughts on that? Is it ok if I just use the reentrant binary for the next MathSAT version?

**Comment by kfriedberger** [comment]
Yes, this is a good idea.
