### ISSUE TITLE
Bug in Z3 quantifier handling

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#12]
3661e14674124de2026216682372d9b99ae0fe28 adds test cases that show a bug in the introspection of quantifiers for Z3 in `Z3UnsafeFormulaManager` or `Z3QuantifiedFormulaManager`.

**Comment by kfriedberger** [comment]
should be fixed with 52f5ed2cae6c2e0958a47572b83e6b8b754f91ab .
