### ISSUE TITLE
Calculating minimum and maximum with Java7 is currently not possible.

### ISSUE THREAD

**Issue by Subaro** [sosy-lab/java-smt#122]
Hello, currently it is not possible to use the minimum and maximum methods with Java 7 because they return the data type Optional<Rational>. I need Java 7, therefore, is there a way to change the return type for the methods to something that is supported by Java 7?

Everything else works fine with Java7.

**Comment by PhilippWendler** [comment]
JavaSMT officially targets Java 8, I am a little bit surprised that so much works on Java 7 :-)

Currently we don't have plans for supporting Java 7, which would take some time, and this time would probably be spent better on supporting Java 9. Is there no chance you can upgrade to Java 8? Java 8 is quite old already (4 years), Java 10 is to be released next week.
