### ISSUE TITLE
Publish new version to Maven Central

### ISSUE THREAD

**Issue by todesking** [sosy-lab/java-smt#123]
The latest version of java-smt in Maven Central is [1.0.1](https://search.maven.org/#artifactdetails|org.sosy-lab|java-smt|1.0.1|jar), aug 2016.

There is lots of improvements since then, why don't you release new one?

**Comment by kfriedberger** [comment]
Our main use-case was an IVY-repository.
Nobody ever asked explicitly about a new Maven release. :-)
I will upload the current version to MavenCentral soon.

We are currently working on a new major release,
thus the current version has most new features included
and contains already most changes in the API.

**Comment by kfriedberger** [comment]
Current version `2.0.0-alpha-43-g775a9d3` was published on MavenCentral
and should appear in [search](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.sosy-lab%22%20AND%20a%3A%22java-smt%22) soon.
From now on we will keep an eye on MavenCentral and update the releases there together with our IVY-repository. ;-)
