### ISSUE TITLE
SmtInterpolFormulaCreator#isNumber(Term t) behavior

### ISSUE THREAD

**Issue by danglotb** [sosy-lab/java-smt#124]
Hi, I am using `java-smt` with the `SMTINTERPOL` solver.

I am encountering a problem that when I want to multiply two `ApplicationTerm`, `java-smt` throws an `UnsupportedException`.

Here find a minimalist example:

```java
public static void main(String[] args) {
        try {
            org.sosy_lab.common.configuration.Configuration config = org.sosy_lab.common.configuration.Configuration.defaultConfiguration();
            LogManager logger = BasicLogManager.create(config);
            ShutdownManager shutdown = ShutdownManager.create();
            SolverContext context = SolverContextFactory.createSolverContext(
                    config, logger, shutdown.getNotifier(), SolverContextFactory.Solvers.SMTINTERPOL);
            FormulaManager fmgr = context.getFormulaManager();
            IntegerFormulaManager imgr = fmgr.getIntegerFormulaManager();
            final NumeralFormula.IntegerFormula param1 = imgr.makeVariable("param1");
            final NumeralFormula.IntegerFormula param2 = imgr.makeVariable("param2");
            final NumeralFormula.IntegerFormula param3 = imgr.makeVariable("param3");
            final NumeralFormula.IntegerFormula param4 = imgr.makeVariable("param4");
            final NumeralFormula.IntegerFormula add = imgr.add(param1, param2);
            final NumeralFormula.IntegerFormula add2 = imgr.add(param3, param4);
            final NumeralFormula.IntegerFormula multiply = imgr.multiply(add, add2);
            System.out.println(multiply.toString());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

The thrown exception is:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsupportedOperationException
	at eu.stamp.project.ex2amplifier.Playground.main(Playground.java:55)
Caused by: java.lang.UnsupportedOperationException
	at org.sosy_lab.java_smt.basicimpl.AbstractNumeralFormulaManager.multiply(AbstractNumeralFormulaManager.java:266)
	at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolNumeralFormulaManager.multiply(SmtInterpolNumeralFormulaManager.java:68)
	at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolNumeralFormulaManager.multiply(SmtInterpolNumeralFormulaManager.java:29)
	at org.sosy_lab.java_smt.basicimpl.AbstractNumeralFormulaManager.multiply(AbstractNumeralFormulaManager.java:255)
	at eu.stamp.project.ex2amplifier.Playground.main(Playground.java:50)
```

The question is: this is the intended behavior or not? Maybe I missed something or did something wrong.

It seems that the method `SmtInterpolFormulaCreator#isNumber(Term t)` return false on the `ApplicationTerm` like `(+ param1 param2)`

Thank you very much!

Cheers,

Benjamin.

**Comment by kfriedberger** [comment]
SMTInterpol does not support multiplication of general terms (like `x * y`), and thus JavaSMT throws an exception. Multiplication with a constant numeral (like `3*x`) is fine.
An ApplicationTerm is an application of a function and can never be a plain number.

**Comment by danglotb** [comment]
Hi @kfriedberger 

> SMTInterpol does not support multiplication of general terms (like x * y)

You mean that other solvers does support such multiplication?

Thank you for your answer!

**Comment by kfriedberger** [comment]
Some solvers support non-linear multiplication,
or they at least try to solve it, with potentially large ressource and time usage. 
Z3, Princess and Mathsat5 support (at least partially) non-linear multiplication.
SMTInterpol fails as soon as you try to `assert` a non-linear term in the prover.
Our implementation fails earlier, e.g., when building such a term.

For Mathsat, we currently check whether one argument is numeric, due to historic reasons.
I will take a further look, maybe we can remove the check in this place now.

**Comment by kfriedberger** [comment]
Update:
There were some improvements in the bindings for linear and non-linear multiplication in 1c0aecff7ec963d5474b28c4502cf8c828d7d287 and 97fcf8274246eba1d253006ca92ad4b1a76dc0a2 .
