### ISSUE TITLE
Update to Z3 4.7.1

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#128]
Z3 4.7.1 is released, but upgrading JavaSMT to it produces a failing test: `VariableNamesTest.testBoolVariableEscaping` (cf. [branch z3-4.7.1](https://github.com/sosy-lab/java-smt/tree/z3-4.7.1) and the [Travis build for it](https://travis-ci.org/sosy-lab/java-smt/jobs/383709040)).

This is related to the escaping of variable names and probably requires that we come to a conclusion for #26 first. If we forbid all variable names with `|` in them, this test would not be a problem (it checks what happens if we create a variable with `|`). However, if we decide otherwise, I do not know what to do to fix this.

**Comment by PhilippWendler** [comment]
It seems that the tests go through after https://github.com/sosy-lab/java-smt/commit/0dc6a4b90ae85eb6dda771894162ea5aa7e35a15. Is there anything left to do before merging [z3-4.7.1](https://github.com/sosy-lab/java-smt/tree/z3-4.7.1)?

**Comment by kfriedberger** [comment]
Rebased, merged, done.
