### ISSUE TITLE
Run Z3 tests on Windows

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#129]
We have a working CI on Windows (AppVeyor), and we claim that it is possible to use JavaSMT with Z3 on Windows by downloading the official Z3 binaries. Thus we should test this.

This should be possible by downloading the Z3 binary release for Windows before running the tests in `.appveyor.yml` (possibly caching it).

**Comment by kfriedberger** [comment]
With #202 solved, Z3 and MathSAT5 are available for Windows now and they are tested via Appveyor.
