### ISSUE TITLE
Decide place for general formula-handling methods

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#13]
The `*FormulaManager` interfaces (except `UnsafeManager`) have the following kinds of methods:
- formula creation and introspection (most of the `*FormulaManager` methods)
- getting formula managers and prover environments of various kinds (in `FormulaManager`)
- serialization (in `FormulaManager`)
- tactic application (in `BooleanFormulaManager`)
- quantifier elimination (in `QuantifiedFormulaManager`)

The latter three are somewhat similar as they are all for `BooleanFormula`s, and they all use or manipulate the complete formula, whereas the methods for basic formula creation only work "locally" (i.e., they create or inspect the top-most operator, but nothing deeper inside).
However, currently these methods are spread over the API and get lost in interface like `BooleanFormulaManager` that have lots of trivial methods.

In the future, there will probably be more such methods if we add further tactics and formula traversal / transformation. For example, the `simplify` and `substitute` methods could also belong to this group (especially if we change them to accept only `BooleanFormula`s).

It would maybe make sense to group these methods in a single place where they are better discoverable. One possible place would be to just put them into `FormulaManager`. Another solution would be to put the into `FormulaManager`, but move the other methods there into a new interface that serves as the entry point (and only as the entry point, with no methods except those for getting instances of formula managers and environments).

**Comment by cheshire** [comment]
I can see the following:

 - [x] Move simplify to `FormulaManager`
 - [x] Move tactics to `FormulaManager`
 - [ ] Move substitution on `BooleanFormula` to `FormulaManager`

`dump` and `parse` are already in `FormulaManager`.

I'm not sure how much sense a new interface makes.
I understand your concern that we start mix the "main entry point" with "various utility methods".
"*View" was originally designed for that, but now it's not in `JavaSMT`.

Maybe we should move (part of) it to JavaSMT and separate out the CPAchecker-specific components?
That is complicated by the fact that CPAchecker *View methods include wrapping by default.

**Comment by PhilippWendler** [comment]
I agree that moving parts of the CPAchecker "view" code to JavaSMT makes sense and should be done over time. Precisely because of this I think it would be good to have a decision on the question of this issue before JavaSMT 1.0.

Putting everything mentioned in `FormulaManager` is certainly a solution, and I do not have a concrete proposal (i.e., a name for a new interface) for a better one. However, I think we agree that too many methods in this interface would become a problem at some point, just look at `FormulaManagerView` for a negative example...

**Comment by cheshire** [comment]
I would prefer to just put such general methods in `FormulaManager`.

I think having a messy class with too many methods (even as messy as `FormulaManagerView`) is a much better problem to have then having a messy class hierarchy, where you don't even know where to look for methods.
