### ISSUE TITLE
Update OptiMathSAT

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#132]
JavaSMT uses OptiMathSAT 1.4.0 from 2016, the current version is <del>1.5.1</del> 1.6.3.

There is a [segfault](https://gitlab.com/sosy-lab/software/cpachecker/-/jobs/74369062) in CPAchecker under Java 10 which occurs in liboptimathsaj.so, so it would be good to update to the latest OptiMathSAT to verify whether this still occurs.

Because the version difference is so large we would need to check whether something has changed in the API (e.g., look at the diff of the `.h` files).

**Comment by kfriedberger** [comment]
The branch https://github.com/sosy-lab/java-smt/tree/optimathsat_update contains some promising changes.

**Comment by kfriedberger** [comment]
Closed via #164.
