### ISSUE TITLE
Issue when extracting free variables / UFs from a BooleanFormula

### ISSUE THREAD

**Issue by cathiec** [sosy-lab/java-smt#135]
I wanted to extract all the free variables / UFs from the BooleanFormula "q(v)", but I got an exception.
This is the code (```ufmgr``` and ```fmgr``` are already defined and the solver is **Z3**):
``` Java
IntegerFormula v = ufmgr.declareAndCallUF("v", FormulaType.IntegerType);
BooleanFormula q = ufmgr.declareAndCallUF("q", FormulaType.BooleanType, v);
fmgr.extractVariablesAndUFs(q);
```
And this is the error message:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Unexpected state: constants not expected
	at org.sosy_lab.java_smt.solvers.z3.Z3FormulaCreator.getDeclarationKind(Z3FormulaCreator.java:493)
	at org.sosy_lab.java_smt.solvers.z3.Z3FormulaCreator.visit(Z3FormulaCreator.java:384)
	at org.sosy_lab.java_smt.solvers.z3.Z3FormulaCreator.visit(Z3FormulaCreator.java:75)
	at org.sosy_lab.java_smt.basicimpl.FormulaCreator.visit(FormulaCreator.java:225)
	at org.sosy_lab.java_smt.basicimpl.FormulaCreator.visitRecursively(FormulaCreator.java:251)
	at org.sosy_lab.java_smt.basicimpl.FormulaCreator.visitRecursively(FormulaCreator.java:238)
	at org.sosy_lab.java_smt.basicimpl.FormulaCreator.extractVariablesAndUFs(FormulaCreator.java:310)
	at org.sosy_lab.java_smt.basicimpl.AbstractFormulaManager.extractVariablesAndUFs(AbstractFormulaManager.java:301)
	at structure.Automaton.isEmpty(Automaton.java:291)
	at app.FOADA.checkEmpty(FOADA.java:104)
	at app.FOADA.main(FOADA.java:146)
```

In addition, I tried this with the solver **PRINCESS**, it worked correctly.

Additional Info:
* JRE System Library = JavaSE-1.8
* Ivy Version = 2.2
* JavaSMT Version = 1.0.1

**Comment by kfriedberger** [comment]
I cannot reproduce the bug with your code using the version `1.0.1` and also with the current version of JavaSMT. The error message in your stacktrace seems to be caused by some weird numeral value, which does not match your code snippet.

You can dump the formula right before the problematic line of code as SMTlib2, i.e., using the function `FormulaManager::dumpFormula(f)`. Could you provide the dump here?

**Comment by cathiec** [comment]
I re-downloaded the Z3 native files version 4.4.1 ("libz3.dylib" and "libz3java.dylib"), and replace my previous z3 native files. Now it doesn't trigger any exception, but the result is not normal.

I use the same code:
```Java
IntegerFormula v = ufmgr.declareAndCallUF("v", FormulaType.IntegerType);
BooleanFormula q = ufmgr.declareAndCallUF("q", FormulaType.BooleanType, v);
System.out.println(fmgr.extractVariablesAndUFs(q));
```
If the solver is PRINCESS, the result is:
```{q=q(v), v=v}```
(This is what we want.)
But if the solver is Z3, the result is:
```{v=v}```
(This is not what we want.)

I re-downloaded the Z3 native files version 4.7.1 ("libz3.dylib" and "libz3java.dylib"), I still get the same exception as before.

I don't know why:
1. The result is not the same when the version of Z3 changes.
2. The result is not the same when using different solvers.

**Comment by kfriedberger** [comment]
This is a really strange bug :-)
Can you give more details on your environment?
- OS: Windows/Linux/Mac?
- Architecture: 32 or 64bit?
I aim to re-create the environment and will try to reproduce the problem.

**Comment by cathiec** [comment]
MacOS 64 bit

**Comment by cathiec** [comment]
I found out where comes from the problem.

The binary files (dynamic libraries) of z3/z3java that I put in the **native folder**:
 ```/.ivy2/cache/org.sosy_lab/native/x86_64-macosx/libz3.dylib```
and
```/.ivy2/cache/org.sosy_lab/native/x86_64-macosx/libz3java.dylib```
are downloaded from the ***microsoft official release*** version 4.4.1.

But the z3 jar file version 4.4.1 automatically downloaded via ***Ivy*** is not the same as the version 4.4.1 provided from microsoft official release (https://github.com/Z3Prover/z3/releases).

I just replaced the z3 jar file (automatically downloaded via Ivy)
```/.ivy2/cache/org.sosy_lab/javasmt-solver-z3/jars/com.microsoft.z3-z3-4.4.1-1558-gf96cfea.jar```
by the one downloaded from the ***microsoft official release***.

Now it works correctly:
```Java
IntegerFormula v = ufmgr.declareAndCallUF("v", FormulaType.IntegerType);
BooleanFormula q = ufmgr.declareAndCallUF("q", FormulaType.BooleanType, v);
System.out.println(fmgr.extractVariablesAndUFs(q));
```
Now the result is:
```
{q=(q v), v=v}
```

Anyway, thanks a lot for your patience and your help.

**Comment by kfriedberger** [comment]
Thanks for your feedback. I assume this ticket can be closed.

We aim to use the official binaries for Z3 in some future release.
Then this issue might no longer appear on user site.
