### ISSUE TITLE
A toy example of JavaSMT Interpolation

### ISSUE THREAD

**Issue by fxs130430** [sosy-lab/java-smt#136]
Hi there,
I'm trying to find a basic example of JavaSMT Craig interpolation in Princess. I don't know how to code it as there are few examples available.
I greatly appreciate a toy example.

**Comment by kfriedberger** [comment]
@fxs130430 
Please take a look at the added example from 3d82714404fa7e5ddb2577734a61fff2bf97382e.
We are open for questions and also for feedback.
