### ISSUE TITLE
Remove most methods for formula introspection

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#14]
I propose to remove most of the `isSomething` methods from formula managers. They should be replaced by the visitors from #5.

Our past experience show that these methods are very error prone, both for implementors and for users. There is no clear overview over which kinds of formulas and operators exist, and thus it happens often that cases are forgotten and these methods return a wrong answer, or that code using these methods forgets to handle a case. This is made worse because there are new cases added from time to time, and neither the existing methods nor the code that uses them is adapted. I believe that there is still a lot of code that does not handle quantifiers or bound variables correctly, for example. This is a problem in CPAchecker, but it would be worse for JavaSMT because we would not even have the chance to adapt all existing code if new kinds of formulas or operators are added.

With a visitor, it would be more clear to implementors for which cases they have to check, and for users, which cases exist. Users could also choose to have a compile time failure each time a new case is added (by implementing the visitor directly), or choose to have a runtime failure by extending from a base visitor that throws UnsupportedOperationException in all cases.

Exceptions for methods that can be kept would most probably include `isTrue()` and `isFalse()`, for example.

**Comment by cheshire** [comment]
For deprecation marking I think it would be better to explain specifically why a method is deprecated (e.g. @Deprecated("please use our visitor")

**Comment by PhilippWendler** [comment]
I added the milestone, because I think at least we should have a decision on this before a version 1.0.

**Comment by cheshire** [comment]
I think we can do this after migrating the CPAchecker away from them (which we can do now).

**Comment by cheshire** [comment]
I'm ready to go ahead with the removal now, please let me now if there are any objections.

**Comment by cheshire** [comment]
IF we do this to the end, that removes like 90% of `UnsafeFormulaManager`. We can remove `.getUnsafeFormulaManager` then, and keep it JavaSMT-private, just for sharing the code (as we can't call `FormulaManager` from `BooleanFormulaManger`).

**Comment by cheshire** [comment]
I think we'll then rename `UnsafeFormulaManager` to `InternalFormulaManager` and emphasize it's just for sharing code.

**Comment by PhilippWendler** [comment]
If it is just internal use, it should be merged with `FormulaCreator`, which also has the same purpose.
