### ISSUE TITLE
Model evaluation of bitvector literals fails for Princess

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#142]
The following code if added to `ModelTest.testEvaluatingConstants` fails for Princess:

```
assertThat(m.evaluate(bvmgr.makeBitvector(32, 1))).isEqualTo(BigInteger.ONE);
```
Instead, `null` is returned.

We should probably test such cases for all theories.

**Comment by kfriedberger** [comment]
Bug in Princess reported to @pruemmer .

**Comment by kfriedberger** [comment]
Nightly build [02-Dec-2018](http://logicrunch.research.it.uu.se/maven/uuverifiers/) of Princess supports the evaluation of simple bitvector constants like `bv0`, `bv123`.
Support for simplifying bitvector expressions with constants like `bv0 + bv1 + bv123` is still missing.
I asked @pruemmer about it.

**Comment by kfriedberger** [comment]
Princess got improved. Lets wait for its next nightly build to re-evaluate our use-case.
