### ISSUE TITLE
Method not found using Gradle dependencies

### ISSUE THREAD

**Issue by iagosd** [sosy-lab/java-smt#145]
Hi all, I am trying to replicate the ALL_SAT example but I can't find the getAssignmentAsFormula() method in Model.ValueAssignment class.

I am using Gradle with java-smt 1.0.1

Is it a feature from the Alpha version or something different between master branch and repository?

Thanks a lot

**Comment by kfriedberger** [comment]
We have recently released JavaSMT 2.0.0 where the method is available. Could you try the new version and provide feedback?

**Comment by iagosd** [comment]
Hi, and thanks for your kind answer!

I'm experiencing troubles with the 2.0.0 gradle signature: on Maven I found the line to add
```
org.sosy-lab:java-smt:2.0.0-alpha-266-g80711a5
```
but it won't work and gives weird crash outputs.

I will retry in this days, keeping you informed.

**Comment by iagosd** [comment]
Hello, 

If I try to compile the 2.0,0 version I get this error:

```
> Could not resolve org.sosy-lab:common:0.3000-323-ge8e29f7.
     Required by:
         project : > org.sosy-lab:java-smt:2.0.0
      > Could not resolve org.sosy-lab:common:0.3000-323-ge8e29f7.
         > Could not get resource 'http://mvn.jasoft.fi/maven2/org/sosy-lab/common/0.3000-323-ge8e29f7/common-0.3000-323-ge8e29f7.pom'.
            > Could not GET 'http://mvn.jasoft.fi/maven2/org/sosy-lab/common/0.3000-323-ge8e29f7/common-0.3000-323-ge8e29f7.pom'.
               > mvn.jasoft.fi
```

**Comment by kfriedberger** [comment]
The release of `org.sosy-lab:common:0.3000-323-ge8e29f7` to Maven was forgotten and done now. Please wait some time (normally some hours) for Maven to synchronize its servers and then try again.

**Comment by kfriedberger** [comment]
Seems to work for now.
