### ISSUE TITLE
More conversions between types

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#152]
Currently the API does not offer a possibility to convert for example between bitvector formulas and integer formulas, although at least MathSAT has support for this. The only type conversions offered are between floats and anything else via `FloatingPointFormulaManager.cast*` (but only conversions between floats and bitvectors are actually implemented), and between integers and rationals (because integers can be used in place of rationals).

We should
- provide a more general API for type conversions
- systematically go through and implement all cases that are supported for each solver

**Comment by kfriedberger** [comment]
Possible conversions are defined by SMTlib.
We might need to check whether or how far the solvers support them.

I would suggest to allow the following conversions:

|from \ to|Int|Real|FP|BV|
|-------|----|----|----|----|
|Int|`=`|`=`|`real2fp`|`nat2bv`|
|Real|`real2int`|`=`|`real2fp`|via FP or BV?|
|FP|via real?|`fp2real`, NaN/Inf?|fp2fp|`ieee_fp2bv`|
|BV|`bv2nat`|`bv2nat`|`ieee_bv2fp`|`extend`/`extract`|

and lets ignore Bool and Array theory.
Some conversions are lossless, others use rounding and lose information.

**Comment by kfriedberger** [comment]
This seems to be sufficiently supported until now.
Lets close this issue until we need more conversions.
