### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#158]
Please update the dependencies, at the very least Truth to 0.46 and SoSy-Lab Common to 0.3000-357-gc47b29f. Truth has made several backwards-incompatible changes in the last releases, and because of this users of JavaSMT cannot use a newer Truth if JavaSMT does not update.

Actually, JavaSMT is several versions behind, probably it is easier to do a step-wise update for each Truth version because several things were marked as deprecated and removed a version later. The [release notes](https://github.com/google/truth/releases) explain the suggested replacements. SoSy-Lab Common might need to be updated via 0.3000-343-gafbf75e corresponding to the Truth updates, too.

**Comment by kfriedberger** [comment]
Fixed with ef3d612f833184cfc926d9328457dca7b674fab6 and e9532811dc5b202052cdf5922a8e5d2c9ded1f97.
A new release version of JavaSMT is coming soon.
