### ISSUE TITLE
Require Java 11?

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#159]
CPAchecker is switching to Java 11, so from our point of view JavaSMT could do this as well. Newer Java brings some features and the build system could be simplified. Are there other users of JavaSMT who still require compatibility with Java 8?

**Comment by kfriedberger** [comment]
Currently no user of JavaSMT has answered and reported any problems with Java 11.
In my opinion, we can change the version to Java 11 soon.

**Comment by PhilippWendler** [comment]
CPAchecker has switched to Java 11, so from our point of view this could be done now.

It might be a good opportunity to check all dependencies for updates and sync the build system from [java-project-template](https://gitlab.com/sosy-lab/software/java-project-template).

For more information about the upgrade, you can look at [this documentation](https://gitlab.com/sosy-lab/software/cpachecker/issues/591#note_210391895) and [the changes that were applied to CPAchecker](https://gitlab.com/sosy-lab/software/cpachecker/compare/03753eaa58dcaa3dfaa14fadc05ac1b9fee10398...145470ae6ff6d87fdd1f8fd48808013a767e8e6f).

**Comment by kfriedberger** [comment]
I will take a look at open PRs and issues first and prepare a latest release for Java8. Then JavaSMT will switch to Java11.

**Comment by PhilippWendler** [comment]
Ping? There have been two minor releases since then.

**Comment by kfriedberger** [comment]
Closed via #178 .
The next release will only support Java 11 (or newer).
