### ISSUE TITLE
Move some of tests from FormulaManagerViewTest to JavaSMT

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#16]

**Comment by cheshire** [comment]
A large chunk of CToFormulaConverterWithArraysTest can be moved as well (it just tests arrays support)

**Comment by stephanlukasczyk** [comment]
Moved the SMT related test cases with commit 8cf377e from CPAchecker's CToFormulaConverterWithArraysTest to SolverTheoriesTest.
