### ISSUE TITLE
Unresolvable Maven dependency

### ISSUE THREAD

**Issue by Ari-Zerner** [sosy-lab/java-smt#167]
Apologies if this isn't the right place to address this.

Resolving this library as a dependency from [Maven](https://mvnrepository.com/artifact/org.sosy-lab/java-smt) is failing. I believe this is because the corresponding [Z3 dependency](https://mvnrepository.com/artifact/org.sosy-lab/javasmt-solver-z3) isn't up to date.

**Comment by kfriedberger** [comment]
That is of course the right place for such a problem.
None of our projects effectively uses Maven, thus such dependency errors might not get noticed automatically.
I will take a look in the Maven build and then report back.

**Comment by kfriedberger** [comment]
The missing library was `Java Common Library` in version `0.3000-357-gc47b29f`. The artifact was uploaded to Maven.
Please note that the optional (!) Maven dependency for the Z3 SMT solver is still outdated. Only the solver `SMTInterpol` is provided in a current version. Currently the installation for other solvers requires some manual effort, as described in [GettingStarted](https://github.com/sosy-lab/java-smt/blob/master/doc/Getting-started.md). We still will need to find a solution for including solver binaries in a more convenient way.

**Comment by PhilippWendler** [comment]
This was already suggested in 2016: #88 

Furthermore, the Maven integration should be continuously tested as suggested in #79 to avoid issues like this one.

But I guess this issue can be closed then?
