### ISSUE TITLE
Update Z3 to upcoming release

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#168]
Z3 has added two new features that are useful for JavaSMT and which should be available in the next release of Z3:
- https://github.com/Z3Prover/z3/issues/867 (SMT2 log file for solver interaction via the API)
- https://github.com/Z3Prover/z3/issues/1006 (Allow interrupts on individual solvers)

As soon as a new release is made, we should upgrade to it. Also related to the upgrade: #116

**Comment by baierd** [comment]
Unfortunately both Issues are not available in Java at the moment. 
I will request Java implementation.
(The Z3 JNI wrapper is pretty good. We could fix it ourselfs and request a PR if need be)

**Comment by kfriedberger** [comment]
This issue is solved for now.
