### ISSUE TITLE
Entry point for Logging*Environment

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#17]
Currently it's just orphaned, as the wrapping was done by the Solver class in CPAchecker.

One solution would be to migrate (some part of) the Solver class to JavaSMT.

**Comment by cheshire** [comment]
Or we can just move it to FormulaManager.
However logging is exposed using an `@Option`, which can't be attached to interfaces.
@PhilippWendler would you hate changing `FormulaManager` to abstract class? Any other solutions?

**Comment by cheshire** [comment]
Oh wait there is `AbstractFormulaManager` already, somehow missed that.

**Comment by cheshire** [comment]
Can anyone shed any light on on-demand wrapping with `InterpolatingProverWithAssumptionsWrapper`?  Shouldn't it be in JavaSMT as well?

**Comment by PhilippWendler** [comment]
What do you want to know about `InterpolatingProverWithAssumptionsWrapper`? How is this related to `Logging*Environment`?

**Comment by cheshire** [comment]
Funny enough it is.

Look at the code in Solver for creating the
InterpolatingEnvironmentWithLogging: it checks whether the
returned environment has assumptions first, and if it doesn't, wraps it
with InterpolatingProverWithAssumptionsWrapper.

I assume it is because the LoggingWrapper implements *WithAssumptions
interface, in order to avoid having
to have two logging wrappers.

This leads to some funny logic, where the environment gets wrapped only if
logging is on.

**Comment by PhilippWendler** [comment]
The code in `Solver` is not like this because of logging. We want to have support for `InterpolatingProverEnvironmentWithAssumptions` no matter which solver is used, but some solvers do not support it, so in that case we use our own implementation. The logging is completely orthogonal to that.

Of course `InterpolatingProverWithAssumptionsWrapper` can be moved to JavaSMT.

**Comment by cheshire** [comment]
Fixed by 6bbe7c6856ff8bb06c1538582f12d2b664e39c1f
