### ISSUE TITLE
Support for abs() on Integer and Floating-Point Theories

### ISSUE THREAD

**Issue by blizzard4591** [sosy-lab/java-smt#173]
Dear developers,
I was trying to encode a program using JavaSMT and found no matching calls on the FormulaManagers for the abs() functions. I am using MathSAT5 as the backend.
Should this be done using an ITE expression or is there some other, more clever way?

Thank you!

**Comment by kfriedberger** [comment]
Hi,
you are right, currently our API does not yet offer `abs(x)` for numerals.
You can easily implement it on top of the API by using `ITE(x>=0,x,-x)`.

It seems as if the function `abs` is part of the SMTlib standard, thus we could add it (for some future release).

**Comment by blizzard4591** [comment]
Ok, will do - Thanks!
