### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#176]
The unit tests for JavaSMT fail since 2019-12-29 ([report](https://sosy-lab.gitlab.io/-/software/java-smt/-/jobs/423018991/artifacts/JUnit.html)). This should be fixed as soon as possible because it will lead to people ignoring test results and new bugs being introduced.

**Comment by kfriedberger** [comment]
They do not fail always, but only sometimes.
This is sometimes related with an overall shortage of memory
and sometimes with a segmentation fault in CVC4 (unknown reason).

**Comment by kfriedberger** [comment]
Seems to be fixed.
