### ISSUE TITLE
SmtInterpol#dequote

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#19]
Hi,

Does anyone know why SMTInterpol `#getName` implementation in `UnsafeFormulaManager` removes vertical bars around the variable name?
That seems very inconsistent across different solvers and in addition tied to the CPAchecker logic.

**Comment by PhilippWendler** [comment]
getName removes the quotes because SMTInterpol adds them itself in some cases. I think it makes sense to guarantee that the when visiting the result of `makeVariable("something"), the name of the variable is exactly the given string.

**Comment by cheshire** [comment]
OK that would do.
