### ISSUE TITLE
Purity of BooleanFormula

### ISSUE THREAD

**Issue by uncttao** [sosy-lab/java-smt#190]
Hi developers, I just would like to know if the data class BooleanFormula is pure, meaning whether feeding a BooleanFormula generated by a BooleanFormulaManager derived from one SolverContext to a prover derived from _another_ SolverContext will cause issues? In other words, can I just treat the class as a pure syntactic description of a formula, or is it reference-sensitive to any particular prover's context? Thanks!

**Comment by kfriedberger** [comment]
Every formula depends on its context and **should not be used** in another context.
Each Formula-object is only a minimalistic wrapper around the SMT solver's own reference.

For exchanging BooleanFormulae between contexts, you should use `FormulaManager.translateFrom(formula, otherContext)`.
