### ISSUE TITLE
New example program for printing supported features

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#192]
It would be nice to have an program in the `example` package that automatically exports the solver capabilities in a simple way.

The program should iterate over all available solvers (alphabetic order) and print their data, for example as a table on cmdline:

| Solver | Version | Theories | Prover-Features |
| --- | --- | --- | --- |
| MathSAT5 | 5.6.3 | Int, Real, FP, BV, Array, ... | Interpolation, UnsatCores |
| ... |

The data should be autogenerated from the existing class instances, i.e., whenever a XFormulaManager is not null, the solver supports the theory X. This might overapproximate the solver's capabilities (if a solver provides the API, but can not solve the query), but is a good starting point for users.

**Comment by baierd** [comment]
Should it include the license as well?

**Comment by kfriedberger** [comment]
No. License is not auto-generated.

**Comment by kfriedberger** [comment]
The programm should detect all features automatically, e.g. by catching exceptions for unsupported features or provers.

**Comment by kfriedberger** [comment]
And then add it into `./runExamples.sh`, as first program.

**Comment by baierd** [comment]
Probably a naive question: since license is important and in every header, why isn't there a datastructure that gives back the license of the current solver?

**Comment by kfriedberger** [comment]
Licensing is a meta-topic that has nothing to do with "features".
We will soon have the Reuse integration that checks for licenses and can report them.

**Comment by kfriedberger** [comment]
But yes, I agree that having the license in the table would be nice to have.

**Comment by baierd** [comment]
Maybe a good opportunity will arise with the Reuse integration. Shouldn't be hard to add to this program.

**Comment by baierd** [comment]
How should AllSat be handled?
It works for every solver in JavaSMT but not every solver can do it natively and we can't discern the two i think.

**Comment by kfriedberger** [comment]
AllSat is not a big feature. Just ignore it.

**Comment by baierd** [comment]
I tried that already because some methods have inconsistent behavior but i ran into a problem. 

Clarification on the inconsistent behavior. For example `UnsatCoreOverAssumptions()` takes an argument. If that's `null` one gets a NullPointerException as expected. Except in MathSAT5, there its fine and it works. I know that that's implementation specific and not really our fault, but weird.

**Comment by kfriedberger** [comment]
It might be better to always expect a nonnull value.
Can you fix the code for MathSAT5, i.e. add some `Preconditions.checkNotNull` into the method.
And then write a JUnit test for the method with `Null` parameter.

**Comment by baierd** [comment]
Sure

**Comment by baierd** [comment]
We excluded MathSat5 in our `unsatCoreWithAssumptionsTest()` in the class `ProverEnvironmentTest` and it doesn't satisfy that example if i try with it. Is UnsatCore /w Assumptions in MathSat5 even usable as one would expect?

**Comment by kfriedberger** [comment]
That might be a bug in the MathSAT5 wrapper implementation.
