### ISSUE TITLE
MathSAT5 does not consistently handle assumptions.

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#194]
_Originally posted by @baierd in https://github.com/sosy-lab/java-smt/issues/192#issuecomment-651909235_

It seems as if MathSAT5 has partial support for assumption solving and that JavaSMT is using this API in a wrong way.
We need to either use the API in a correct way or remove the invalid code from JavaSMT.

**Comment by baierd** [comment]
UnsatCoreOverAssumptions is fixed with commit [169eaf1](https://github.com/sosy-lab/java-smt/commit/169eaf1c54e6e8eaf14a22b41608a92e39cd1440) and the test is re-enabled.

**Comment by kfriedberger** [comment]
The problem was just a forgotten case for a satisfiable query?
The commit looks good.

**Comment by baierd** [comment]
Yes.
We could however add a `checkState(!closed)` as some solvers have it and some don't, and its probably a good idea.

I have a question though: SMTInterpol needs a empty environment for `UnsatCoreOverAssumptions` while the others don't care about that. Is that just a special case for SMTInterpol or is the idea behind `UnsatCoreOverAssumptions` always to check the assumptions only?
(Yes i know SMTInterpol does not support assumptions and we cheat a little by entering them as fixed formulas and pop them afterwards)

**Comment by kfriedberger** [comment]
That is special for SMTInterpol only.

The idea behind assumption solving is that you can annotate parts of the stack (either as direct annotation `SOME_COMPLEX_EXPR :named PRED1` or as additional constraints like `PRED1 == SOME_COMPLEX_EXPR`) and then enable or disable those parts via the given list of assumptions (which contains `PRED1` or `NOT PRED1`).
