### ISSUE TITLE
AppVeyor tests fail most of the time

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#197]
The tests run by AppVeyor seem to fail often, for at least several months now. This is bad because it could mean that there is a real instability in JavaSMT that should be solved, or at least it will mean that newly introduced problems will be overlooked.

**Comment by kfriedberger** [comment]
I already noticed the problem. There seems to be a SegFault somewhere. But I do not know how to get more information about it from AppVeyor. I will take a deeper look soon.

**Comment by kfriedberger** [comment]
Reducing the number of artifact files from JUnit helped.
The builds are valid since several weeks now.
Closing this issue.
