### ISSUE TITLE
Make visitors interfaces

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#20]
(better to start new issues I guess instead of adding everything into one)

Should we make our visitors interfaces? It is not really necessary to let them be classes, and it would follow the typical convention. Default visitors etc. would stay abstract classes of course.

**Comment by cheshire** [comment]
But we would still need to have a base class.
We already have a lot of visitor-related classes, and that would just add more.

**Comment by PhilippWendler** [comment]
I think the base visitor should only be an interface and not an abstract class at all.
