### ISSUE TITLE
Installation of CVC4

### ISSUE THREAD

**Issue by proteusGIT** [sosy-lab/java-smt#203]
The explanations for installation do not mention all solvers.

E.g. CVC4 is missing. The website seems to have only an .exe for windows.
Which files are needed and where to get them?

**Comment by kfriedberger** [comment]
### For Linux users:
We provide all necessary files in [our Ivy repository](https://www.sosy-lab.org/ivy/org.sosy_lab/).
When using Ant/Ivy as build tool, those dependencies are automatically installed. 
For manual instalation, please check the dependencies in the ivy-xml file to get the correct version.
CVC4 is build [from source](https://github.com/kfriedberger/CVC4) using the steps written in the [build script](https://github.com/sosy-lab/java-smt/blob/0f5fcfb65843d2acae84c46063b28cc9bc32728e/build/build-publish-solvers.xml#L103).

### For Windows users:
We are currently working on [supporting more solvers on more operating systems](https://github.com/sosy-lab/java-smt/tree/windows-support).
CVC4 can be [build from source for Windows using Mingw-w64](https://github.com/kfriedberger/CVC4/blob/master/INSTALL.md#cross-compiling-for-windows).
I will test this and report back here. 
My plan is to also provide those binaries in our Ivy repository.

**Comment by kfriedberger** [comment]
A quick initial test showed several problems when compiling the Java bindings for Windows. If really needed, I will investigate further.
However, for myself and our group, running other solvers than CVC4 on Windows has higher priority.

**Comment by kfriedberger** [comment]
Current status:
CVC4 dropped support for Java and will re-implement it in the future.
Until then we stay with the existing version, which is the revision shortly before they dropped Java support.
The existing release does not allow to build a Windows binary with Java bindings.
This might be an option conflict in the build script, further documentation and information is currently missing.

**Comment by kfriedberger** [comment]
CVC4 is superseeded by CVC5. JavaSMT will provide both solvers for some time and then drop support for CVC4.
