### ISSUE TITLE
Travis config outdated

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#212]
The repository contains a `.travis.yml` that is outdated (attempts to build with Java 8). I suggest to either delete it or upgrade it if Travis should be used.

**Comment by kfriedberger** [comment]
I think that we Travis can be replaced with Gitlab-CI completely and we can remove Travis.
I will take a look.

**Comment by kfriedberger** [comment]
Fixed with 1239417d5e001c7fa944c850d15cd60bc8bcd1d8
