### ISSUE TITLE
Declaring functions for Z3 does not work with FormulaManager.parse

### ISSUE THREAD

**Issue by jfh1911** [sosy-lab/java-smt#216]
I am using JavaSMT with the Maven build (which is by the way really nice, thanks a lot :smile: )

I tried to load a SMT formula via `FormulaManager.parse()`, containing an uninterpreted function.
Hence, I created the function using the `UFManager`.
Although it is created, Z3 throws the exception `(error "line 1 column 81: unknown function/constant $main_inv1")`

To reproduce the error, I created a new testcase, copied it to the test dir in the example maven project and run `mvn test`
(I also added a test-leading for MathSat5 and Princess, with both works).

The file is attached.

[ParsingTest.txt](https://github.com/sosy-lab/java-smt/files/5925975/ParsingTest.txt)

**Comment by kfriedberger** [comment]
Thanks for your report. You might have found a bug. :beetle: 
We will check whether this problem is intended behaviour of Z3 and then try to fix it.

**Comment by baierd** [comment]
@jfh1911 
Temporary fix: declare your functions in the SMT-LIB2 query directly.
For your example add to the front of your formula String: (declare-fun $main_inv1 (Int Int Int) Bool)

Usually we reuse the by the API declared functions etc. and give them to the parser additional to the query entered.
We don't do this in Z3 as it throws an exception if you enter the same declaration multiple times.
Meaning this is fine for the other solvers.

However, we are trying to fixing this!

Ideas to fix it:
-Catch exception and read conflict from it to delete the conflicting term from the query.
-Cache declarations and symbols in the *FormulaCreator(s) and give them to the parser

Ideas by @kfriedberger. I just tested it and wrote it down.

**Comment by jfh1911** [comment]
Thanks for the fast response and the hint :-)

I just realized that (not really surprisingly). the same issue occurs for free variables (which are also declared as functions)
