### ISSUE TITLE
Allow customization of loading native libraries

### ISSUE THREAD

**Issue by lorenzleutgeb** [sosy-lab/java-smt#225]
In an existing project, that I would like to migrate to JavaSMT, I bundle `libz3java.so` (and other shared objects) to be contained within the JAR. This way, the JAR becomes more self-contained and therefore portable. It also increases in size, and defeats the purpose of dynamic linking, I am well aware.

For the sake of clarity, the relevant code in the project looks like this:
 * [`Z3Support.load`](https://github.com/lorenzleutgeb/lac/blob/44e82721adfcb9453f722118e11b111f30bba427/src/main/java/xyz/leutgeb/lorenz/lac/util/Z3Support.java#L26-L30)
 * [`Util.loadLibrary`](https://github.com/lorenzleutgeb/lac/blob/44e82721adfcb9453f722118e11b111f30bba427/src/main/java/xyz/leutgeb/lorenz/lac/util/Util.java#L145-L179)
 * [`Native.loadLibraryFromPath`](https://github.com/lorenzleutgeb/lac/blob/44e82721adfcb9453f722118e11b111f30bba427/src/main/java/xyz/leutgeb/lorenz/lac/util/Native.java#L38-L76)
 
The approach is incompatible with JavaSMT, because loading is not configurable:
https://github.com/sosy-lab/java-smt/blob/664fc291f42c07042cb210dec3f36f91cd13e520/src/org/sosy_lab/java_smt/solvers/z3/Z3SolverContext.java#L116-L132

As a developer using the library I'd like to see more pluggable customization options here. I have two suggestions:
 - Add a "bring your own native dependencies" mode. When enabled, JavaSMT should just not load any libraries, i.e. make no calls to `System.loadLibrary`, but assume that they already are loaded.
 - Allow providing a "strategy" for loading libraries.

**Comment by kfriedberger** [comment]
Thank you for your interest in JavaSMT.
This issue affects all native solvers, and the idea to make the loading process of libraries more configurable sounds reasonable.
We will take a further look soon and try to find a solution.

**Comment by kfriedberger** [comment]
See #247 for further progress.
