### ISSUE TITLE
Provide introspection for SMTLib-standardized functions

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#23]
In CPAchecker it is necessary to traverse formulas and find out if-then-else nodes (even with non-boolean operands).

To support this, a method `visitIfThenElse` could be added to `FormulaVisitor`. Adding this method has the advantage that the first operand could actually be typed as `BooleanFormula`, whereas this is lost with `visitFunction`. This makes the common case of traversing specifically the boolean parts of a formula easier and avoids the need for casts. From an SMT viewpoint the if-then-else function is also different enough from other functions to warrant a separate method, because of the boolean operand, which otherwise only the normal boolean operators have.

Regardless of whether this method is added, other users might need introspection for other non-boolean standard functions as well. Using the `String name` attribute is not possible because different solvers return different names for the same function.

If we actually want to support such use cases, we could expose an enum with values for the most common standard functions in `visitFunction`. It would need a value `OTHER` because we cannot expect to handle all functions. If UFs and standard functions continue to be handled by the same function, the enum would also get a value `UF` and the boolean parameter would go away, though when looking at the two possible methods their signature is so different that I think two methods are better:
```
R visitUF(Formula f, String name, List<Formula> args, UFDeclaration decl);
R visitOperator(Formula f, Operator type, String name, List<Formula> args, Function<List<Formula>, Formula> newApplicationConstructor);
```

Providing only the `String name` and a separate utility for parsing the name into an enum of common functions is not good because there are a lot of names that would need to be handled that are solver specific, so this utility would actually have to be solver-specific as well, and then there is no advantage over adding it directly to the visit method.

**Comment by cheshire** [comment]
`UfDeclaration` is actually not that useful as a parameter, since one can as easily use `declareAndCall` from the `FunctionFormulaManager`.
I also prefer to keep the number of required dependencies to learn to a minimum, and `UfDeclaration` is completely avoidable.

I was thinking about the following interface:

```java
  enum DeclarationKind {

    // Boolean operations
    AND,
    NOT,
    OR,
    IFF,
    ITE,
    XOR,
    IMPLIES,

    // Simple arithmetic
    SUB,
    ADD,
    DIV,
    MUL,
    MODULO,

    // Simple comparison
    LT,
    LTE,
    GT,
    GTE,
    EQ,

    UF,

    /**
     * Solvers support a lot of different built-in theories.
     * We enforce standardization only across a small subset.
     */
    OTHER
  }

  class Declaration {
    String name;
    DeclarationKind kind;
  }

  R visitFunction(
      Formula f,
      List<? extends Formula> args,
      Declaration declaration,
      Function<List<? extends Formula>, ? extends Formula> newApplicationConstructor,
      boolean isUninterpreted);
```

**Comment by cheshire** [comment]
We need to be very careful about standardizing declaration names for arithmetic.

For comparison and arithmetic we have to decide whether they work across all sorts (I would say "yes" across rationals and integers, and maybe add separate functions for bitvectors).

**Comment by cheshire** [comment]
See latest commits, this should work.

**Comment by cheshire** [comment]
I am closing this one in favor of continuing discussion in #5, as the basic implementation is done.
