### ISSUE TITLE
Unnecessary test files in JavaSMT JARs

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#231]
Recent [JAR files](https://www.sosy-lab.org/ivy/org.sosy_lab/java-smt/java-smt-3.7.0-115-gf3c5dad3.jar) for JavaSMT contain two files `org/sosy_lab/java_smt/test/*.smt2` with 650 kB in size (1/5 of the total JAR content). These files are useless, because they seem to be for JavaSMT's own tests, which are not bundled in the JAR. So I suggest to remove them.

**Comment by kfriedberger** [comment]
Thanks for the report. The smt2-files will be removed in the next release.
