### ISSUE TITLE
Inproper variable naming due to escape-characters

### ISSUE THREAD

**Issue by baierd** [sosy-lab/java-smt#239]
The assumption that the name/toString() representation a variable returns should be the same as the name used to create it does not seem to hold for some names using Z3 and CVC4.

This can be seen on the branch [cvc4_quantifier](https://github.com/sosy-lab/java-smt/tree/cvc4_quantifier), in the failing tests.
Note: i've added a assert that checks variable.toString() == original name String.

It seems like the solvers use `|` as escape-characters, to surround some names, i.e. `(exit)`, `,` or spaces.

Either we remove these test-cases for the specified solvers, or we need to find another solution.
In the case of CVC4 it might be easier than Z3, as the variable cache of CVC4 is in our code.

**Comment by baierd** [comment]
We already have some excluded Strings/Chars for the `isValidName` method (and others connected to this one) in the `FormulaManager`. Some invalid names are catched by this method, but not all.
But as this problem only seems to occur in 2 solvers (CVC4, Z3), would it make sense to extend the invalid Strings in the `FormulaManager`? @kfriedberger

**Comment by baierd** [comment]
Most failing names fail because of some small char like `"` somewhere in the String. 
An incomplete list of currently failing names is below. The linebreak `\\n` and some redundant or repeating names are excluded.  

  
```
ሴሴሴ
:::
[[[
{
}
 " can occur too 
 af klj ^*0 asfe2 (&*)&(#^ $ > > >?" ’]]984 af klj ^*0 asfe2 (&*)&(#^ $ > > >?" ’]]984 af klj ^*0 asfe2 (&*)&(#^ $ > > >?" ’]]984
[
}}}
]

[]
"""
 af klj ^*0 asfe2 (&*)&(#^ $ > > >?" ’]]984
 "
 this is a quoted symbol 
"""""""""
(
(((
)
(exit)
 this is a quoted symbol  this is a quoted symbol  this is a quoted symbol 
,
,,,
""""""
ሴ
[][][]
⺀⺀⺀
:
(exit)(exit)(exit)
]]]
""

⺀
```

**Comment by kfriedberger** [comment]
We do not guarantee that "Formula#toString" returns a valid name, we explicitly [*warn* about escaped or unescaped result](https://sosy-lab.github.io/java-smt/api/org/sosy_lab/java_smt/api/Formula.html#toString()) when calling that method. 

Thus, I would not do anything here.
