### ISSUE TITLE
Integrate Z3 Java API

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#24]
Try the provided Java API, compare the performance with the JNI one we have.

**Comment by cheshire** [comment]
great!

**Comment by cheshire** [comment]
Currently blocked by not requiring to use a custom Z3 fork.

**Comment by cheshire** [comment]
@kfriedberger Current approach results in much pain for me when I'm trying to update Z3 version or even simply figure out what version are we using.
What about storing the patch with your changes in JavaSMT repo, and dynamically applying it (and reverting afterwards) on publish-z3 task?

**Comment by kfriedberger** [comment]
Our ANT-task only uses the binaries from the Z3-directory, which would be compiled with the wrong sources. Thus, having the patch in our own repository does not help for our wrapper "Z3Java".
We have seen that their own Java-API needs more memory, we perhaps should just remove "Z3Java" from JavaSMT, if we cannot convince the authors of Z3 to include our patch.
The old version "Z3" seems to work without any patching. It would remain usable.

**Comment by cheshire** [comment]
@kfriedberger I think we should ship the .patch file and either ask the user to apply it before compiling Z3, or even move Z3 compilation into the ANT task as well. Just doing former would be still miles better than what we have now.

Regarding support for Z3Java, I think in future we should use a hybrid approach, where we would use the JNI bindings provided by Z3 (just the Java function calls which are marked as "native"), and do the rest ourselves.
This way we would get both high performance and would get to avoid the performance penalty associated with Z3 Java bindings.

**Comment by PhilippWendler** [comment]
What is actually the purpose of our patch? If it is only the lookup for the native library from Java, I *think* we should be able to do this by using a custom class loader.

**Comment by kfriedberger** [comment]
There are 2 dependencies here:
1) Java/JNI needs to find `libz3java.so`. This works fine.
2) `libz3java.so` needs to find `libz3.so`. Therefore we have the patch. `libz3.so` is not located in any known system-library-path and thus cannot be loaded with some system-loading-mechanism. Is there a way to use the Java-class-loader to set `LD_LIBRARY_PATH` or similar?

**Comment by cheshire** [comment]
@kfriedberger before we go into this, new cmake build system for Z3 promises to deliver what we need without patching. I think we should evaluate https://github.com/Z3Prover/z3/pull/568 first.

**Comment by PhilippWendler** [comment]
> 2) libz3java.so needs to find libz3.so. Therefore we have the patch. libz3.so is not located in any known system-library-path and thus cannot be loaded with some system-loading-mechanism. Is there a way to use the Java-class-loader to set LD_LIBRARY_PATH or similar?

We cannot really set `LD_LIBRARY_PATH` from Java, I investigated this, but maybe we could patch the Z3 binary? Cf. http://stackoverflow.com/q/13769141/396730 (`chrpath`/`patchelf`)

**Comment by cheshire** [comment]
@PhilippWendler I thought about patching binaries, and if we can do that it's definitely more preferable than having a fork.

**Comment by delcypher** [comment]
Just observing this conversation I don't really do Java but shouldn't you be able to modify the ``java.library.path`` property by doing something like?

```java
System.setProperty(“java.library.path”, “/path/to/library”);
```

to control what directories are searched for libraries?

**Comment by PhilippWendler** [comment]
No, you cannot set `java.library.path` from inside the Java process, because the property is read only once a startup and later changes to it are ignored.

**Comment by delcypher** [comment]
@PhilippWendler Okay, shows how much I know about Java... ;)

**Comment by cheshire** [comment]
@kfriedberger Cristoph Wintersteiger has pointed out the possiblity of using class loader to modify the java library path (http://blog.cedarsoft.com/2010/11/setting-java-library-path-programmatically/) can that be used?

**Comment by cheshire** [comment]
@kfriedberger OK so I finally got really sick of having to use a custom Z3 version, so I've committed a change based on the hack suggested by Cristoph Wintersteiger which allows us to use normal Z3.

**Comment by PhilippWendler** [comment]
What? Do you really think it is wise to use reflection to change a private field of a central class of the JVM internals?

I strongly suggest to revert this.

**Comment by PhilippWendler** [comment]
Please do not include a JavaSMT version that includes this code in CPAchecker until this has been discussed.

**Comment by cheshire** [comment]
Yes, since it only runs if Z3JAVA is selected (which is almost never)
