### ISSUE TITLE
distinct method for BV

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#240]
Is there any fundamental reason with the `BitvectorManager` does not have a `distinct` method similar to the one in `NumeralFormulaManager`?

If there is no such reason, is there any plan to add support for this?

**Comment by baierd** [comment]
I can't give you a concrete answer as to why we don't support it, but it seems like only a few solvers support this feature (Z3 and CVC4 do support it).
It may be possible to support it for these two solvers if @kfriedberger wants to.

**Comment by kfriedberger** [comment]
First, not all solvers support it and second, no user requested it so far. :smile: 

Plan:
As this change might break interface/source compatibility, we might consider it for the next larger release. We can provide a default implementation (first idea: a basic approach with quadratic runtime and formula size) for those solvers, that do not support it. For solvers with direct support, we can forward the call to their API.
