### ISSUE TITLE
Contexts using different solvers generate not SAT-equivalent formulae

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#242]
I'm getting different solutions for "the same" generated formula when using `Z3` and `PRINCESS`. The first thing I did was to dump the formula to a file and call both solvers from the console. While doing this, I discovered that the generated formulae were actually different (not just Object-wise which was expected, but they are actually not SAT-equivalent).
- If I dump the formula to a file setting the solver to `Z3` and then run both binaries on the generated file, the results of both tools is `UNSAT`*. 
- If I dump the formula to a file setting the solver to `PRINCESS` and then run both binaries on the generated file, the results of both tools is `SAT`.

*This is the result I could consider correct from the point of view of verification

The generated formulae are not too big and I tried to inspect them manually, but both solvers generate constraints in different orders, they are thing like `distinct` for which `Z3` uses the keyword while `PRINCESS` creates a whole formula saying that every pair is `!=`, each solver uses different abbreviations (`let` in `Z3` and `define-fun abbrev_` in `PRINCESS `), etc, so I could not get much information from this either.

I took a look to the implementation of `PrincessBooleanFormulaManager`, `PrincessNumeralFormulaManager` and `PrincessIntegerFormulaManager` which are the ones used by my tool, but I could not spot anything problematic there either.

Since the formulae are generated programatically from an input program (i.e. the formula is not fix in my code) I don't really know how I can report this properly.

Any suggestion on how I could debug this further? Is there any way to compare two formulae created using the API in exactly the same way (i.e. formulae that by construction should be SAT-equivalent)?

**Comment by PhilippWendler** [comment]
First thoughts:

Does looking at satisfying assignments for the satisfiable variant and unsat cores for the unsat variant help? These could give some indication where the formulas differ.

If looking at these manually does not help, you could construct a formula that states that both of your formulas should be equivalent, give that to an SMT solver and ask for an unsat core.

Using more than two SMT solvers with JavaSMT might help to decide which of them is more likely to be correct.

**Comment by kfriedberger** [comment]
How are you providing the formulas in the first place? Are the formulae given as SMTLIB or generated via the API of JavaSMT?

In a similar case, the problem of different SAT/UNSAT results from different solvers appeared after reading the same SMTLIB file:  
The currently released version of our Princess bindings (in JavaSMT 3.9.0 and earlier versions) contains a bug ([mentioned here](https://github.com/sosy-lab/java-smt/issues/232#issuecomment-864777537)) that appears when reading SMTLIB with `declare-fun`. We already have a workaround and a fix in Princess (added to JavaSMT in 6907b882debc72dbe83c826a45da09659a12ffcb), but there was no futher release of JavaSMT since then.
Maybe your case is similar.

**Comment by hernanponcedeleon** [comment]
> Does looking at satisfying assignments for the satisfiable variant and unsat cores for the unsat variant help? These could give some indication where the formulas differ.

The variable assignment is small and easy to check manually, but the UNSAT core is not, thus I don't think this is easy.

> If looking at these manually does not help, you could construct a formula that states that both of your formulas should be equivalent, give that to an SMT solver and ask for an unsat core.

I tried creating two context (one using each solver) and then adding all constraints (same set of constraints, one for each context) to one prover created from the first constraint. JavaSMT was complaining that `Cannot get the formula info of type Z3BooleanFormula in the Solver!` (I guess it cannot retrieve some information from the formulae generated using `PRINCESS`). Based on your suggestion I guess there is a way of doing so, but how I did it was not correct.

> Using more than two SMT solvers with JavaSMT might help to decide which of them is more likely to be correct.

I'm pretty confident that the problem is with `PRINCESS`: both `Z3` and `SMTINTERPOL` give `UNSAT` and this is the correct result from the verification point of view (for which I'm generating the formula).



> How are you providing the formulas in the first place? Are the formulae given as SMTLIB or generated via the API of JavaSMT?

Via the API (this is what I meant by "the formulae are generated programatically").

> In a similar case, the problem of different SAT/UNSAT results from different solvers appeared after reading the same SMTLIB file:
> The currently released version of our Princess bindings (in JavaSMT 3.9.0 and earlier versions) contains a bug ([mentioned here](https://github.com/sosy-lab/java-smt/issues/232#issuecomment-864777537)) that appears when reading SMTLIB with `declare-fun`. We already have a workaround and a fix in Princess (added to JavaSMT in [6907b88](https://github.com/sosy-lab/java-smt/commit/6907b882debc72dbe83c826a45da09659a12ffcb)), but there was no futher release of JavaSMT since then.

I don't think this is the reason. As I said, I generated the formulae using the API and then dumped each formula (`f1` generated by `Z3` and `f2` generated by `PRINCESS`) to a file. Both binaries return the same result for `f1`. The same happens for `f2`. However the results of `f1` and `f2` differ.

**Comment by hernanponcedeleon** [comment]
While digging deeper into this, I encounter something unexpected. The following code
```
prover.addConstraint(A);
prover.addConstraint(B);
        
try {
    Path fileName = Path.of("dummy.smt2");
    BufferedWriter writer = new BufferedWriter(new FileWriter(fileName.toString()));
    BooleanFormula all = ctx.getFormulaManager().getBooleanFormulaManager().and(
        A,
        B,
    );
writer.write(ctx.getFormulaManager().dumpFormula(all).toString());
writer.close();
			
ProverEnvironment prover2 = ctx.newProverEnvironment(ProverOptions.GENERATE_MODELS);
prover2.addConstraint(ctx.getFormulaManager().parse(Files.readString(fileName)));

System.out.println(prover.isUnsat());
System.out.println(prover2.isUnsat());
```
prints out
```
true
false
```

If I comment the first two lines (adding the constraints to the prover), the generated files (attached) greatly differ. In particular, many of the variables disappear.

I suppose there is some kind of formula simplification going on. Am I right? Is it normal that variables disappear?

[Archive.zip](https://github.com/sosy-lab/java-smt/files/6931963/Archive.zip)

This behaviour is only observable when using `Z3`. If I set the solver to `PRINCESS`, both printed statements match.

**Comment by kfriedberger** [comment]
The solver can simplify constraints, but it should not remove any symbol that is related to satisfiability.
For example:
- `x == x` can be simplified to `true`, and the symbol `x` does no longer appear here. 
- `(x == y) && false` can be simplified to `false`, and both symbols are no longer relevant.

I am not sure what happens in your case.

**Comment by hernanponcedeleon** [comment]
I think I found the source of the problem. The following method

https://github.com/sosy-lab/java-smt/blob/8c0fdce6dcbdc98356c9255e69ce857263de538c/src/org/sosy_lab/java_smt/solvers/princess/PrincessBooleanFormulaManager.java#L120

allows to make the following simplification (`<->` is an instance of `IBinFormula`)
```
(a <-> b) & (a<->c) ----> a <-> (b & c)
```
which is unsound. On the left-hand side, if `b=1`, then both `a` and `c` must be 1. However in the right-hand side they can still be `0`.

**Comment by kfriedberger** [comment]
Thanks for the hint. We are planning to provide an updated release version of JavaSMT soon.

**Comment by hernanponcedeleon** [comment]
I built the version with the fix locally and I can confirmed that the bug is fixed.
