### ISSUE TITLE
Request to load Z3 native libraries optionally via configuration.

### ISSUE THREAD

**Issue by raulraja** [sosy-lab/java-smt#245]
Hi, 

I'm working on a project where I depend on java-smt inside a Kotlin compiler plugin.

Since the Kotlin compiler frequently runs in daemon mode, it loads new compilations using the same parent classloader.
As new compilations come through for each different module, I need to instantiate a z3 solver context.

Currently, the Z3 solver context in java-smt explicitly loads the native libraries like this.
https://github.com/sosy-lab/java-smt/blob/8c0fdce6dcbdc98356c9255e69ce857263de538c/src/org/sosy_lab/java_smt/solvers/z3/Z3SolverContext.java#L120-L133

I want to turn off that portion of code via configuration or some other way since I have no control over how the kotlin compiler process will get started (Gradle, manually), etc. I have no way to set java.library.paths for my users, and even when I do so, it complains the native libraries are loaded twice the second time it runs in daemon mode.

For that reason, I instead depend on `z3-turnkey` to configure the native libraries, which seems to work when I access the Z3 APIs directly without issues.

I suppose this is not just an issue with Z3 libs?

Would you be open to a PR that allows a config value that, when added, turns off explicit loading the native libraries of the different solvers? 

Thanks!

**Comment by raulraja** [comment]
Maybe a dup or related to https://github.com/sosy-lab/java-smt/issues/225

**Comment by kfriedberger** [comment]
This feature was requested several times now, for different use cases. I will add such a flag.

**Comment by raulraja** [comment]
thanks @kfriedberger!

**Comment by kfriedberger** [comment]
See #247 for further progress.

It should be sufficient to use the new constructor parameter and implement a NOOP as loading strategy.
