### ISSUE TITLE
Usage Question: Multithreading and translateFrom(BooleanFormula, FormulaManager)

### ISSUE THREAD

**Issue by pmw95** [sosy-lab/java-smt#254]
[JavaSMTs Readme.txt states](https://github.com/sosy-lab/java-smt#multithreading-support):

> The solvers Z3(w and w/o Optimization), SMTInterpol, Princess, MathSAT5, Boolector and CVC4 support multithreading, provided that different threads use different contexts, and all operations on a single context are performed from a single thread.

1. In [CPAchecker](https://github.com/sosy-lab/cpachecker), the [PredicateCPA](https://github.com/sosy-lab/cpachecker/blob/trunk/src/org/sosy_lab/cpachecker/cpa/predicate/PredicateCPA.java) creates and encapsulates a [Solver](https://github.com/sosy-lab/cpachecker/blob/trunk/src/org/sosy_lab/cpachecker/util/predicates/smt/Solver.java) instance; which in turn encapsulates, manages and creates a [SolverContext](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/api/SolverContext.java). [PredicateCPA](https://github.com/sosy-lab/cpachecker/blob/trunk/src/org/sosy_lab/cpachecker/cpa/predicate/PredicateCPA.java) does not provide the user with the ability to control or set the underlying instances of  [Solver](https://github.com/sosy-lab/cpachecker/blob/trunk/src/org/sosy_lab/cpachecker/util/predicates/smt/Solver.java) and [SolverContext](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/api/SolverContext.java). If an analysis creates independent instances of [PredicateCPA](https://github.com/sosy-lab/cpachecker/blob/trunk/src/org/sosy_lab/cpachecker/cpa/predicate/PredicateCPA.java) in separate threads, does this invoke the situation described in the quote (i.e. one actual/native solver instance gets created, and each CPA obtains its own context; multi-threaded use of such CPAs is supported)?

2. Does the limitation that separate threads must use separate contexts apply to all solvers, or do some of them allow concurrent access on the same context (while probably establishing specific requirements regarding which kinds of access might be allowed)? 

If the strict but reasonable limitation from 2. applies to all solvers, the only option for sharing formulas between separate threads is provided by [translateFrom(BooleanFormula, FormulaManager)](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/api/FormulaManager.java#L246) in [FormulaManager](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/api/FormulaManager.java). With this method, an application can move a [BooleanFormula](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/api/BooleanFormula.java) from the solver context of one thread  to the solver context of another thread, thus enabling the combination of such formulas in the target thread (e. g. logical conjunction).

The JavaDoc of this method states:
> Default implementation relies on string serialization [...], but each solver may implement more efficient translation between its own contexts.

Please consider the following situation:
An analysis with a [PredicateCPA](https://github.com/sosy-lab/cpachecker/blob/trunk/src/org/sosy_lab/cpachecker/cpa/predicate/PredicateCPA.java) completes in a thread (a). This thread now sends a formula derived by this analysis to a separate thread (b). In (a), the [PredicateCPA](https://github.com/sosy-lab/cpachecker/blob/trunk/src/org/sosy_lab/cpachecker/cpa/predicate/PredicateCPA.java) starts to operate again (i.e. the algorithm gets invoked again), but in a situation where the information available in the solver at the time the formula was created is not required any more (let's say it now runs on another independent portion of the program). In thread (b), the method [translateFrom(BooleanFormula, FormulaManager)](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/api/FormulaManager.java#L246) is used (together with a reference to the [FormulaManager](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/api/FormulaManager.java) from the solver in (a)) to translate the formula into the context of (b). These two operations - a new, independent run of the [PredicateCPA](https://github.com/sosy-lab/cpachecker/blob/trunk/src/org/sosy_lab/cpachecker/cpa/predicate/PredicateCPA.java) in (a), and the call to [translateFrom(BooleanFormula, FormulaManager)](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/api/FormulaManager.java#L246) in (b) can happen simultaneously. 

3. Is [translateFrom(BooleanFormula, FormulaManager)](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/api/FormulaManager.java#L246) safe for such usage?

**Comment by kfriedberger** [comment]
Hi @pmw95.
Thanks for your interest in JavaSMT and CPAchecker. I will try to answer your questions:

1. Yes, the described situation seems to exactly match the notion of "separate contexts". Thus, independent concurrent usage should be possible.

2. This is a question I can not answer completely, because it depends on the solver itself.
    For MathSAT, multi-threaded usage with only one solver-instance might even work, because JavaSMT uses the reentrant version, i.e., all solver calls for MathSAT should be threadsafe. However, this might need more testing and evaluation. For other native solvers, this feature is not available and , e.g., I can confirm that CVC4 and Yices crash quite easily if used in that way. 

3. Yes, it should be, otherwise that is a bug in JavaSMT or the solver.  
    However, I have not yet tested this, because multi-threaded testing is hard.

**Comment by kfriedberger** [comment]
Sorry, there was a wrong statement in the text above:
MathSAT does *not* support multiple threads on one single solver instance. 
Based on [this JUnit test](https://github.com/sosy-lab/java-smt/blob/97bddc35d13f2f38e782ba4f476592f5894992b3/src/org/sosy_lab/java_smt/test/SolverConcurrencyTest.java#L120), only CVC4 supports multi-threaded usage (i.e., multiple prover stacks) of a single context.

**Comment by pmw95** [comment]
Hey @kfriedberger, thanks a lot for addressing this issue so quickly! 
This helps a lot and answers my questions so far :slightly_smiling_face:

**Comment by baierd** [comment]
I've added a test for this in commit [9cf636f878e15d160cb0ebcdf8fac7af267dbd6c](https://github.com/sosy-lab/java-smt/commit/9cf636f878e15d160cb0ebcdf8fac7af267dbd6c). Seems like its no problem for most solvers. 
CVC4 does not support formula translation currently and Princess has a weird problem that i need to look into.

**Comment by pmw95** [comment]
@baierd Very cool how you transformed my description into a test, and thanks for sharing your insights :+1:
