### ISSUE TITLE
Boolector 3.2.2

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#258]
The release notes of version `3.11.0` mention the updated solver `Boolector 3.2.2`.
However there seems to be no updated version in the maven repository [here](https://search.maven.org/search?q=org.sosy-lab).
Am I missing something?

**Comment by baierd** [comment]
We are currently working on updating Boolector to 3.2.2.
The reason as to why it is not available yet is that we are adding the capability to create a model to it in this update.
However it is nearly done and should be available shortly!

**Comment by kfriedberger** [comment]
Actually, Boolector 3.2.2-g0783aa84 is already available in [our Ivy repositoy](https://svn.sosy-lab.org/software/ivy/repository/org.sosy_lab/javasmt-solver-boolector/), but somehow was not yet synced to Maven.
I will take a look.

**Comment by kfriedberger** [comment]
Fixed.
The Boolector library in version 3.2.2-g0783aa84 was released into the OSS repository a few minutes ago.
It should appear in the public Maven repository in a few hours.

The interface of the Boolector library in version 3.2.1 and 3.2.2 did not change, so JavaSMT will work fine with either of them.
We will update our example projects under `doc/examples/` with the new version number.
