### ISSUE TITLE
Provide access to solver-internal statistics

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#260]
Several solvers provide some kind of internal statistics for clauses, conflicts, solving time, etc.
There are users requesting access to this data through JavaSMT.

The overall format depends on the solver. We might choose to export data in a default key-value-mapping.
Some solvers provide statistics per context (e.g., MathSAT), other solvers provide statistics per prover (e.g., SMTInterpol and Z3).
We need to take a look at the usefulness and provide either one or two new methods in the API.

For MathSAT, it seems as if the corresponding method was never included in compilation and the native C-bindings need to be touched.

For Boolector, it seems as if statistics are written to stdout instead to String. This is bad behaviour. Maybe we can redirect the stream in the native C-bindings (otherwise we ignore those statistics).

**Comment by baierd** [comment]
When compiling Boolector you can also set the `--time-stats` flag to enable compilation with time statistics.

**Comment by baierd** [comment]
I've added a new C function + JNI method for your use case in Boolector.

**Comment by kfriedberger** [comment]
closed with #261
