### ISSUE TITLE
[FEATURE REQUEST] Support for BV signed reminder

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#264]
Would it be possible to add support for signed reminder in the theory of bit-vectors? AFAIK, most of the solvers supported by java-smt (at least [z3](https://z3prover.github.io/api/html/namespacez3.html#a102bfab2e468949f979c20b8f4c6c63d), [cvc4](https://github.com/CVC4/CVC4-archived/blob/e117a12641c3715888207dff071f7c6714b82f54/src/theory/bv/kinds#L63), [cvc5](https://cvc5.github.io/docs/cvc5-0.0.7/api/cpp/kind.html?highlight=srem#_CPPv4N4cvc53api4Kind14BITVECTOR_SREME), [mathsat-5](https://mathsat.fbk.eu/apireference.html#ab2f5a5015f152dbf1fdf4908f629f05d), [boolector](https://github.com/Boolector/boolector/blob/e7aba964f69cd52dbe509e46e818a4411b316cd3/src/btorbv.h#L344)) can handle that operation.

**Comment by kfriedberger** [comment]
We already have support in the BitvectorFormulaManager for signed and unsigned reminder in form of signed and unsigned modulo ([see here](https://github.com/sosy-lab/java-smt/blob/28e93043ef1ad17103e21c8688a1f662494c9a55/src/org/sosy_lab/java_smt/api/BitvectorFormulaManager.java#L72)).
I assume that these method is sufficient. We could improve documentation here :-)

**Comment by hernanponcedeleon** [comment]
There seems to be a difference between the `mod` and `rem` operators (AFAIK it is related to the returned sign, see e.g. the link in my previous msg for `cvc4`). While most of the solvers seem to make this distinction (i.e. they support both `mod` and (signed/unsigned)`rem`), java-smt does not.

**Comment by kfriedberger** [comment]
The MOD operator seems to be missing in some solvers (e.g., MathSAT) and is also not declared in the [SMTLIB standard for BV](https://smtlib.cs.uiowa.edu/theories-FixedSizeBitVectors.shtml).
MOD is only a sibling of REM: the unsigned variant is identical, the signed variant only differs in the sign computation.
It can be computed from the result of REM on user side, i.e. outside of JavaSMT.
I would like to avoid the handling of MOD, to keep the interface simple and to avoid further confusion.

**Comment by hernanponcedeleon** [comment]
Since it is not part of the standard and it can be computed from our side, I agree the best is to keep the interface simple.

**Comment by kfriedberger** [comment]
Your simple feature request let us detect two bugs, one in JavaSMT's solver bindings for Boolector and one in Princess. Both bugs could have been avoided by a more detailed testsuite. The work on improved documentation, tests, and bug-fixing happens in #265.
Thus, feel free to request or ask about more stuff :-) Best.
