### ISSUE TITLE
Problem with statistics and MATHSAT5

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#267]
I get the following error when using `MATHSAT5` and trying to call `prover.getStatistics()`
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.lang.String org.sosy_lab.java_smt.solvers.mathsat5.Mathsat5NativeApi.msat_get_search_stats(long)'
	at org.sosy_lab.java_smt.solvers.mathsat5.Mathsat5NativeApi.msat_get_search_stats(Native Method)
	at org.sosy_lab.java_smt.solvers.mathsat5.Mathsat5AbstractProver.getStatistics(Mathsat5AbstractProver.java:183)
```
Any idea what the problem might be?

**Comment by kfriedberger** [comment]
This looks like a incompatibility of JavaSMT and MathSAT, which is not expected.
Can you give some more information:
- JavaSMT and MathSAT version?
- operating system?
- general setup, i.e., installed via Maven or Ant/Ivy?
- did you manually copy around libraries, or is MathSAT already available in some system path?

**Comment by hernanponcedeleon** [comment]
> * JavaSMT and MathSAT version?

JavaSMT: x3.12.0
MathSAT: version 5.6.6 (218275631c24) (Apr 23 2021 08:35:29, gmp 6.1.2, gcc 7.5.0, 64-bit, reentrant)

> * operating system?

  Operating System: Ubuntu 18.04.4 LTS
            Kernel: Linux 5.4.0-96-generic
      Architecture: x86-64

In case it might be relevant, I'm running this inside an lxc container.

> * general setup, i.e., installed via Maven or Ant/Ivy?

Maven

> * did you manually copy around libraries, or is MathSAT already available in some system path?

Dependencies are copied similar to the example [here](https://github.com/sosy-lab/java-smt/blob/master/doc/Example-Maven-Project/pom.xml). Concretely we have this
```
<plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>3.1.1</version>
            <executions>
              <execution>
                <id>copy</id>
                <phase>initialize</phase>
                <goals>
                  <goal>copy</goal>
                </goals>
              </execution>
              <execution>
                <id>copy-dependencies</id>
                <phase>validate</phase>
                <goals>
                  <goal>copy-dependencies</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <outputDirectory>${project.dependency.path}</outputDirectory>
              <artifactItems>

                <!-- MathSAT5 native library (Linux) -->
                <artifactItem>
                  <groupId>org.sosy-lab</groupId>
                  <artifactId>javasmt-solver-mathsat5</artifactId>
                  <type>so</type>
                  <classifier>libmathsat5j</classifier>
                  <destFileName>libmathsat5j.so</destFileName>
                </artifactItem>

...
```

**Comment by baierd** [comment]
Ok this is interesting! You use the correct and most up to date JavaSMT and Mathsat5 versions. I've tried some things to recreate your problem but could not in the end. (I found that Mathsat5 SIGSEVs if you try to get the statistics in a closed prover, but thats not your problem i think and its fixed now.)

Could you provide some more information @hernanponcedeleon?
Does this always happen for you or only for a certain query? If its a certain query could you send it to us? Did you use any options or did you use quantifiers/arrays with bitvectors or quantifiers, excessive creation/closing of provers/push/pop?

I'm gonna look into lxc containers next for my search.

**Comment by kfriedberger** [comment]
It looks to me as if your MathSAT library is outdated, because of the message about the missing function for statistics.

There are multiple versions of MathSAT 5.6.6 denoted as `sosy0` and `sosy1`, because we included the previoulsy missing support for statistics (since sosy0) and additional stack-related methods (since sosy1) in our JNI-bindings.

Could you please check the exact version number that is used in the Maven-file?
The latest versions are available in the Maven repository: https://search.maven.org/artifact/org.sosy-lab/javasmt-solver-mathsat5

**Comment by baierd** [comment]
@kfriedberger is right. I just tested it with the versions `5.6.6`, `5.6.6-sosy0` and `5.6.6-sosy1`. In `5.6.6` i can recreate your error. 

(I was under the assumption that the version string gives you the date of the compiliation of our wrapper! But it only gives the date of the compiliation of the Mathsat5 version, which is the same for all 3)

**Comment by hernanponcedeleon** [comment]
That was indeed the problem. I confirm by that using `5.6.6-sosy1`, I'm able to extract the statistics. Thanks a lot for your help @baierd and @kfriedberger
