### ISSUE TITLE
Update MathSAT5 from 5.6.6 to 5.6.7

### ISSUE THREAD

**Issue by baierd** [sosy-lab/java-smt#269]
MathSAT5 has released a new version 5.6.7 with some [fixes](https://mathsat.fbk.eu/releasenotes.html). We should update our version accordingly.

**Comment by kfriedberger** [comment]
MathSAT 5.6.7 requires a version of GCC newer than the one shipped with Ubuntu 18.04.
Details: A referenced method named `_ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev` that is not available in GCC 7.

The latest version 4.8.17 of Z3 also removed the support for Ubuntu 18.04 (which currently leads to some failing CI-tests). 

With this update of MathSAT, we plan to also remove the support for Ubuntu 18.04 and switch to Ubuntu 20.04 as basic platform.
