### ISSUE TITLE
Usable ant task for checkstyle

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#27]
It's painful to have to read both entire `Checkstyle.xml` and `Checkstyle.Test.xml` to find any errors.
The grep task which is used for Travis should be available through `ant` as well.

**Comment by PhilippWendler** [comment]
Why are you looking at `Checkstyle.xml` and `Checkstyle.Test.xml`? Don't you have IDE integration for Checkstyle?

If you really want to avoid using the IDE, there are two HTML files produced by `ant checkstyle`, both have the total number of errors in the first line, and you can click on the class names with errors to jump right to the error description.

**Comment by cheshire** [comment]
Actually, I've failed to configure the checkstyle plugin for IntelliJ :P Somehow it didn't want to work with our configuration...

As for the HTML file, I want to do it in the terminal, and I definitely don't want to launch the browser just to see a couple of lines.

**Comment by stieglma** [comment]
This is not really hard to achieve... See  34022d7e15bd69daf39bb28c0fd0061929ca93f2
