### ISSUE TITLE
CVC5 solver not in maven repository

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#284]
The new (3.14.2) release of java-smt [is already in the maven repository](https://repo.maven.apache.org/maven2/org/sosy-lab/java-smt/3.14.2/). However `javasmt-solver-cvc5` [is not](https://repo.maven.apache.org/maven2/org/sosy-lab/). Since this [is already in the ivy repository](https://www.sosy-lab.org/ivy/org.sosy_lab/javasmt-solver-cvc5/), I assume there was a problem when pushing to maven.

**Comment by kfriedberger** [comment]
Thanks for reporting. This issue is already known. 😄 
A Maven release of the CVC5 library is coming soon. ⏳ 
I need to update the publication script and trigger the publication manually.
I will report here when finished.

**Comment by kfriedberger** [comment]
Scripts are fixed now: f92458dad166b99ca65a5f4bda54c2c47735edbe.
Example projects are updated: efb344752c352437ad7a5591a65cac2132d31c90.
CVC5 is now also available via Maven.
