### ISSUE TITLE
Support for non-persistent models

### ISSUE THREAD

**Issue by ThomasHaas** [sosy-lab/java-smt#285]
Would it be possible to add support for non-persistent model objects, i.e., models that are only valid as long as no new SAT-check was performed?
Such models are sufficient for refinement-based implementations (e.g., CEGAR) and might be substantially faster.

As was discussed in #278, MathSAT5 might be substantially faster with non-persistent models.
The new CVC5 Solver shows similar performance problems due to creating fully persistent copies of the native model (this time, the copies are made on the JavaSMT side).
This makes both of these solvers unnecessarily slow, possibly unusable in many refinement-based approaches.
This is unfortunate, because both of these solvers seem to have good solving performance, which ends up getting dominated by model construction times.

**Comment by kfriedberger** [comment]
For CVC4 and CVC5, there actually is a potentially exponential overhead in model construction.

We will take a detailed look soon.

**Comment by ThomasHaas** [comment]
Sounds great, thank you!
