### ISSUE TITLE
`translateFrom` for `IntegerFormulae`

### ISSUE THREAD

**Issue by beatbrot** [sosy-lab/java-smt#287]
Hey guys :)

I am wondering, how it is possible to use `FormulaManager#translateFrom(BooleanFormula, FormulaManager)` with an `IntegerFormula`.

I already checked `FormulaManager`  and `IntegerFormulaManager` without success. 

Thanks for your help!

**Comment by baierd** [comment]
Since you have to build a Boolean formula to assert it later on anyway, you can just build your Boolean formula in your current solver and then translate it.

**Comment by kfriedberger** [comment]
Most solvers provide translation only for Boolean formulas, because the default input/output format for formulas is an encoding as assertions in SMTLIB2.
