### ISSUE TITLE
Avoid unnecessary and unclear abbreviations

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#29]
In several places, the JavaSMT uses abbreviations like `OptEnvironment`, `FuncDecl`, `visitFuncApp`, etc. The full names are typically easier to read, better to understand, and are more consistent with the rest of the API.

For example, there is `visitFuncApp`, but `visitFreeVariable` is not named `visitFreeVar`. `OptEnvironment` could mean other things as well, `OptimizationProverEnvironment` or `OptimizingProverEnvironment` makes it clear what it is about.

Thus I think the API should be cleared up on these and similar points and made easier and more consistent.

**Comment by cheshire** [comment]
Should this be closed?

**Comment by PhilippWendler** [comment]
Not sure, did anybody check the remainder of the API for similar cases? (I just mentioned what I found by chance.)

**Comment by cheshire** [comment]
Haven't really found any.
