### ISSUE TITLE
CVC5 Interpolation

### ISSUE THREAD

**Issue by baierd** [sosy-lab/java-smt#293]
CVC5 uses a different interpolation interpretation than what we support in our API. However, they can be transformed into one another.

We use the following definition of [Craig-Interpolation](https://doi.org/10.2307/2963593):

For a pair of formulas φ− and φ+ such that φ− ∧ φ+ is
unsatisfiable, a Craig interpolant ψ is a formula that fulfills
the following requirements:
1) the implication φ− ⇒ ψ holds,
2) the conjunction ψ ∧ φ+ is unsatisfiable, and
3) ψ only contains symbols that occur in both φ− and φ+.

In CVC5 φ− ⇒ ψ and ψ ⇒ φ+ are with φ+ and φ- being valid.
(Does valid mean SAT or UNSAT?!)

This means that if we negate φ+, we receive the correct interpolant under the assumption that its the same interpretation of satisfiablity.

We should test this.

**Comment by kfriedberger** [comment]
In SMT theory, the validity of a formula is defined as "there is at least one satisfying model for it".

For this context, it might be better not to test it, but to proof it. Someones life might depend on it. :smiley:

**Comment by baierd** [comment]
@nianzelee

**Comment by Po-Chun-Chien** [comment]
> In CVC5 φ− ⇒ ψ and ψ ⇒ φ+ are with φ+ and φ- being valid. (Does valid mean SAT or UNSAT?!)

@baierd What you have written here seems to deviate from their API documentation.

From the [Javadoc](https://cvc5.github.io/docs/cvc5-1.0.2/api/java/io/github/cvc5/Solver.html#getInterpolant(io.github.cvc5.Term)) of `Solver#getInterpolant`:

> Returns:
> A Term I such that A->I and I->B are valid, where A is the current set of assertions and B is given in the input by conj, or the null term if such a term cannot be found.

So, it should be the case that both A->I and I->B are valid, but **NOT** A and B are valid.
And in this context, a formula is *valid* iff it is true under every interpretation (cf. tautologies in propositional logic).

**Comment by baierd** [comment]
I think that's how we interpreted it in our internal discussion.

Update on this issue: we are certain that the proposed changes above lead to the same interpolation procedure. @RSoegtrop currently works on implementing it the way described above.

**Comment by Po-Chun-Chien** [comment]
> I think that's how we interpreted it in our internal discussion.
> 
> Update on this issue: we are certain that the proposed changes above lead to the same interpolation procedure. @RSoegtrop currently works on implementing it the way described above.

Good to know. I really look forward to it.

**Comment by RSoegtrop** [comment]
@baierd Could you please review my take on [CVC5InterpolationProver](https://github.com/sosy-lab/java-smt/blob/ab8abc9ff4e793bc8969029053d59cc1b58da069/src/org/sosy_lab/java_smt/solvers/cvc5/CVC5InterpolatingProver.java)? `Interpolation` and `SequentialInterpolation` should work. I left some ideas on `TreeInterpolation` and marked them as experimental. 
Some Tests in `InterpolatingProverTest` fail to terminate (seem to get stuck in the CVC5 Interpolation API Call).

**Comment by kfriedberger** [comment]
@RSoegtrop Could you create a proper pull-request for the code changes in your branch, such that a review can be performed via Github?
