### ISSUE TITLE
Unable to update MathSAT past 5.6.5

### ISSUE THREAD

**Issue by breandan** [sosy-lab/java-smt#296]
There seems there is some error in the POM file. Whenever I attempt to update MathSAT to [`5.6.6`](https://repo.maven.apache.org/maven2/org/sosy-lab/javasmt-solver-mathsat5/5.6.6/javasmt-solver-mathsat5-5.6.6.pom) or [`5.6.8`](https://repo.maven.apache.org/maven2/org/sosy-lab/javasmt-solver-mathsat5/5.6.8/javasmt-solver-mathsat5-5.6.8.pom) (published on Maven Central), I encounter the following error:

```
   > Could not resolve org.sosy-lab:javasmt-solver-mathsat5:5.6.6.
     Required by:
         project :
      > Could not resolve org.sosy-lab:javasmt-solver-mathsat5:5.6.6.
         > Could not parse POM https://repo.maven.apache.org/maven2/org/sosy-lab/javasmt-solver-mathsat5/5.6.6/javasmt-solver-mathsat5-5.6.6.pom
            > java.lang.NullPointerException (no error message)
```

I configured Gradle to use the `repositories` as shown the example [`build.gradle.kts` file](https://github.com/sosy-lab/java-smt/blob/master/doc/Example-Gradle-Project-Kotlin/build.gradle.kts):

```
repositories {
  mavenCentral {
    metadataSources {
      mavenPom()
    }
  }
  mavenCentral {
    metadataSources {
      artifact()
    }
  }
}
```

**Comment by kfriedberger** [comment]
We will take a look within the next days.
Gradle is not our main development tool.

**Comment by tamal78** [comment]
Happy to help for any documentation.I can't understand the issue here can yoy please elaborate what to change

**Comment by kfriedberger** [comment]
We are still analyzing the issue.

- It looks like Gradle expects every pom-file to contain a versioning for the library, and aborts or crashed otherwise.
- Our first suspicion is that we have simplified too much some time ago: e784c4fc1aa654369372ff665609bb82da2dc450

**Comment by baierd** [comment]
@breandan which Gradle version are you using?

**Comment by baierd** [comment]
I've tested Mathsat 5.6.8 and 5.6.6 with Gradle version 7.6.1 and ivy and Maven central (together and each exclusively) and had no issues in the Gradle, nor the Gradle-Kotlin project. Once you give me your Gradle version ill try again with that exact version. Else i'll need a minimal working example of your build.gradle please.

**Comment by breandan** [comment]
I am on Gradle `8.0.1`. It should be possible to reproduce this error by running the following command:

```
git clone --depth 1 git@github.com:breandan/galoisenne.git && cd galoisenne && sed -i '' 's/5.6.5/5.6.8/g' build.gradle.kts && ./gradlew jvmTest --tests "ai.hypergraph.kaliningraph.smt.TestSMT"
```

**Comment by baierd** [comment]
Ah now i see :D
add :libmathsat5j@so to the artifact identifier to pull the .so directly, i.e. `"org.sosy-lab:javasmt-solver-mathsat5:5.6.8:libmathsat5j@so"`
