### ISSUE TITLE
String solver of cvc5 has many incompatible errors

### ISSUE THREAD

**Issue by xiaoxiongwang** [sosy-lab/java-smt#299]
```java
 SolverContext context = SolverContextFactory.createSolverContext(
                config, logger, shutdown.getNotifier(), SolverContextFactory.Solvers.CVC5);
StringFormula s = smgr.makeVariable("s");
BooleanFormula constraint2 = smgr.contains(s, smgr.makeString("hello world"));
```
It reports error: Exception in thread "main" io.github.cvc5.CVC5ApiException: Operator table.product expects two bags. Found two terms of types 'String' and 'String' respectively.

```java
 SolverContext context = SolverContextFactory.createSolverContext(
                config, logger, shutdown.getNotifier(), SolverContextFactory.Solvers.CVC5);
StringFormula s = smgr.makeVariable("s");
BooleanFormula constraint2 = smgr.prefix(s, smgr.makeString("hello world"));
```
It reports error: 
Exception in thread "main" io.github.cvc5.CVC5ApiException: Invalid kind 'STRING_REPLACE', expected Terms with kind STRING_REPLACE must have at least 3 children and at most 3 children (the one under construction has 2)
        at io.github.cvc5.Solver.mkTerm(Native Method)
        at io.github.cvc5.Solver.mkTerm(Solver.java:521)
        at org.sosy_lab.java_smt.solvers.cvc5.CVC5StringFormulaManager.prefix(CVC5StringFormulaManager.java:77)
        at org.sosy_lab.java_smt.solvers.cvc5.CVC5StringFormulaManager.prefix(CVC5StringFormulaManager.java:19)
        at org.sosy_lab.java_smt.basicimpl.AbstractStringFormulaManager.prefix(AbstractStringFormulaManager.java:116)

**Comment by kfriedberger** [comment]
It would be good to know more details:
- What is your version of JavaSMT and CVC5?
- operating system?

**Comment by xiaoxiongwang** [comment]
> It would be good to know more details:
> 
> * What is your version of JavaSMT and CVC5?
> * operating system?
> 
> From the given information, I can not yet reproduce the issue.
> 
> **Just a guess:** Did you use a self-compiled or incompatible version of CVC5 where the operators are enumerated differently?
1.My version of CVC5 is commit d87874506a956c1d9f97233fff38ee25945e32d2 of https://github.com/cvc5/cvc5 and My version of JavaSMT is 3.14.2
2.My system is Ubuntu 18.04

**Comment by xiaoxiongwang** [comment]
> self-compiled

The CVC5 is indeed a self-compiled version.

**Comment by baierd** [comment]
We can't really debug custom builds. We can however update CVC5 to the release version from march. Hopefully that will solve your issue.

**Comment by xiaoxiongwang** [comment]
> We can't really debug custom builds. We can however update CVC5 to the release version from march. Hopefully that will solve your issue.

Thanks very much.

**Comment by kfriedberger** [comment]
The update to CVC5 v1.0.5 is available in Ivy.
I will publish CVC5 to Maven during the day and then prepare the next release of JavaSMT.

**Comment by kfriedberger** [comment]
CVC5 changed its internal naming for the library from `libcvc5.so` to `libcvc5.so.1`. Having an older version of CVC5 lying around might cause issues with incompatible operation enumerations.

**Comment by kfriedberger** [comment]
I am not sure whether this issue will bring any more insights. Thus, we will close it.
