### ISSUE TITLE
Add Tactics for Formula Rewriting

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#3]
Z3 supports several tactics for rewriting formulas. We should implement the most useful ones for the other solvers (in the `basicimpl` package such that they can be reused) and expose them.

**Comment by PhilippWendler** [comment]
There should also be tests for these tactics, both for our default implementations (to ensure they are correct) as well as for the solver's implementations (to ensure they match our expectations).

**Comment by cheshire** [comment]
Thomas did an excellent job of writing tests. @stieglma I think this one can be closed?

**Comment by stieglma** [comment]
Currently only the default tactics are tested, but it should be easy to expand these tests to also test the native implementation if there is one available

**Comment by cheshire** [comment]
I don't think it's our job to test native implementations though?..

**Comment by PhilippWendler** [comment]
> I don't think it's our job to test native implementations though?..

As I said, it would be good to have tests that ensure that the solver's implementation matches what we expect from it.

For example, does every solver rewrite non-boolean ITEs for NNF tactic?

**Comment by cheshire** [comment]
Point taken, I'll expand those.

**Comment by cheshire** [comment]
I would prefer to remove the method `Tactic#applyDefault` altogether, the point is that we should get consistently correct results across all solvers, what is the point of explicitly requesting default implementation?

**Comment by PhilippWendler** [comment]
Exactly, that's why the method is discouraged and why it is called `applyDefault` instead of `apply`. However, there needs to be some public entry point to the tactics implementation because they are called from a different package.

**Comment by cheshire** [comment]
Well there is a public entry point (`NNFVisitor`), the question is whether it is worth it to make an explicit connection between the value in the enum and the implementation.

**Comment by PhilippWendler** [comment]
I would suggest to rename `applyTactic` to `applyFormulaRewriting` or similar, this is more descriptive and can also be understood by people that are not familiar with Z3.

**Comment by cheshire** [comment]
Hm `tactic` is standard for automatic theorem provers.
I'm going to close this as tactics are implemented, re-open for more specific issues.
