### ISSUE TITLE
Iterating through function applications in Model API in Z3

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#32]
@stahlbauer (not sure who wrote that code originally) --- even though that Model API looks like it should iterate through functions as well, the code for Z3 was only iterating through "constants" = 0-argument functions.

Should the new iteration be fixed? E.g. iterating through constants followed by iterating through the function applications.

**Comment by PhilippWendler** [comment]
Yes, we certainly need to have everything in the model, including function applications. Not sure why this is missing.

**Comment by cheshire** [comment]
@PhilippWendler This is tricky.
What do you expect as a `key` parameter for those?
E.g. if we have asserted `( = (fun a) 3)`,
would you expect `(fun a)` to be a parameter? or `(fun 1)`, because the interpretation of `a` happens to be `1` in that particular model?

**Comment by cheshire** [comment]
For Z3 there is no API to get either of those, short of resorting to tricks we have used for creating iterators for Princess and SmtInterpol.

**Comment by cheshire** [comment]
Mathsat5 substitutes the actual value for any arguments in the iterator.

**Comment by PhilippWendler** [comment]
I do not know whether `(fun 1)` or `(fun a)` would be better, maybe the former is easier and we would not need to change existing code in CPAchecker?

In any case, having a partial model of UFs is important because otherwise CPAchecker cannot output anything about heap values on error paths.

**Comment by cheshire** [comment]
Currently it does not work only for Z3.

We have a choice of either contacting Z3 folk asking for a suitable API, or just resorting to the hack used for Princess and SmtInterpol (keep track of asserted formulas, mine them for used UFs and variables, iterate through those).
Any preferences?

**Comment by cheshire** [comment]
The code for this is a very good argument on why we should use Java API.
