### ISSUE TITLE
Easier way for extracting formula information?

### ISSUE THREAD

**Issue by thebesttv** [sosy-lab/java-smt#326]
Hello, I am trying to find an easier way to get some information about a formula.  For example, I want to determine if a formula is a single variable, or if it is the EQ function (e.g. `(= a b)`).  Right now the only way I can think of is using function visitor like this:
```java
        // is single variable
        fmgr.visit(expr, new DefaultFormulaVisitor<Boolean>() {
            @Override
            protected Boolean visitDefault(Formula f) {
                return false;
            }

            @Override
            public Boolean visitFreeVariable(Formula f, String name) {
                return true;
            }
        });
        // is EQ function
        fmgr.visit(expr, new DefaultFormulaVisitor<Boolean>() {
            @Override
            protected Boolean visitDefault(Formula f) {
                return false;
            }

            @Override
            public Boolean visitFunction(Formula f, List<Formula> args, FunctionDeclaration<?> functionDeclaration) {
                return functionDeclaration.getKind() == FunctionDeclarationKind.EQ;
            }
        });
```
Is there an easier way without using function visitor?
For example, something like `formula.isFreeVariable()`?

**Comment by kfriedberger** [comment]
Hello @thebesttv.
Your code snippets are correct. This is the best solution in JavaSMT to check for free variables or equality operations.
If the code is too complex to read, then you can move the code into a utility class and simply call `Util.isFreeVariable(formula, fmgr)`.
Best.

**Comment by thebesttv** [comment]
Thanks!
