### ISSUE TITLE
Possible memory leak when using CVC5

### ISSUE THREAD

**Issue by thebesttv** [sosy-lab/java-smt#327]
There seems to be a memory leak when using CVC5 to create lots of `SolverContext` objects.
The following code eats up all available memory very quickly:
```java
        while (true) {
            try (SolverContext context = SolverContextFactory.createSolverContext(
                    Configuration.defaultConfiguration(),
                    LogManager.createNullLogManager(),
                    ShutdownNotifier.createDummy(),
                    SolverContextFactory.Solvers.CVC5)) {
            }
        }
```
The problem does not occur when Z3 is used.

Calling `solver.deletePointer()` and `Context.deletePointers()` in CVC5 API seems to solve this problem:
```java
        while (true) {
            try (SolverContext context = SolverContextFactory.createSolverContext(
                    Configuration.defaultConfiguration(),
                    LogManager.createNullLogManager(),
                    ShutdownNotifier.createDummy(),
                    SolverContextFactory.Solvers.CVC5)) {
                Field solverField = getField(CVC5SolverContext.class, "solver");
                solverField.setAccessible(true);
                Solver solver = (Solver) solverField.get(context);

                solver.deletePointer();
                Context.deletePointers();
            }
        }
```
[This](https://github.com/cvc5/cvc5/pull/9147#issuecomment-1256837849) may be related.

**Comment by baierd** [comment]
Fixed as far as possible with [81a96dd42ad37dbb39e208ba4da06bc5fe604893](https://github.com/sosy-lab/java-smt/commit/81a96dd42ad37dbb39e208ba4da06bc5fe604893).
Unfortunately we can't provide full memory cleanup as the `Context.deletePointers();` method deletes all references to all existing contexts, not just the one being closed.
