### ISSUE TITLE
Trying out the new OpenSMT

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#341]
I am eager to try the new javaSMT (not a surprised at this point I guess XD) and I noticed something about OpenSMT.

As usual, there seems to be a delay with the new version being published in the maven repository (both the new java-smt version and the library associated to the new solver). Probably it will get in sync soon, but I wanted to point it out just in case.

What I noticed it is really missing and would be really useful, is the description of how to add the dependency in the [Example Maven Project](https://github.com/sosy-lab/java-smt/blob/master/doc/Example-Maven-Project/pom.xml).

**Comment by kfriedberger** [comment]
Hi Hernan,

thanks for watching JavaSMT so eagerly. :-)
The update of the Maven example project will happen later today.

I already published JavaSMT 4.1.0 and OpenSMT to Maven yesterday evening. It just needs a few hours for syncing ... I have no idea why it takes so long :zzz:.

Best.
