### ISSUE TITLE
JavaSMT: Z3 crashes with GENERATE_UNSAT_CORE

### ISSUE THREAD

**Issue by baoluomeng** [sosy-lab/java-smt#351]
Hello,

I am not sure if this is a z3 issue or a JavaSMT issue. I am using z3 with 4.12.2 and 4.12.4 through JavaSMT 4.1.0 with GENERATE_UNSAT_CORE option ONLY. My machine is a Mac OS Ventura 13.3.1 with Intel chips.

For a simple problem below, JavaSMT with z3 4.12.4 throws an exception as below. With z3 4.12.2, the exception is the same except that the line number is 415. 

ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 416
UNEXPECTED CODE WAS REACHED.
Z3 4.12.4.0

```
(set-option :produce-unsat-cores true)
(set-info :status unsat)
(declare-fun a () Real)
(declare-fun b () Real)
(assert (=> (= a 0) (= b 2)))
(assert (= a 0))
(assert (= b 3))
(check-sat)
(get-unsat-core) 
```
I was able to run z3 4.12.2 binary on the same example without any issues. Not sure if this is an issue related to the info passing from JavaSMT to Z3. 

However, with GENERATE_MODELS option ONLY, JavaSMT with z3 runs successfully on the same problem.

**Comment by baoluomeng** [comment]
Please ignore the above SMT-LIB example. That was not able to reproduce the exception. 

Below is the Java code to reproduce the exception. 

```java
    public static void test2() {
        Configuration config = Configuration.defaultConfiguration();
        LogManager logger = null;
        try {
            logger = BasicLogManager.create(config);
        } catch (InvalidConfigurationException e) {
            e.printStackTrace();
        }
        ShutdownNotifier notifier = ShutdownNotifier.createDummy();
        try (SolverContext context =
                SolverContextFactory.createSolverContext(config, logger, notifier, Solvers.Z3)) {
            RationalFormulaManager rmgr = context.getFormulaManager().getRationalFormulaManager();
            BooleanFormulaManager bfmr = context.getFormulaManager().getBooleanFormulaManager();
            try (ProverEnvironment prover =
                    context.newProverEnvironment(ProverOptions.GENERATE_UNSAT_CORE)) {
                RationalFormula a = rmgr.makeVariable("a");
                RationalFormula b = rmgr.makeVariable("b");
                BooleanFormula aEq0 = rmgr.equal(a, rmgr.makeNumber(0));
                BooleanFormula bEq2 = rmgr.equal(b, rmgr.makeNumber(2));
                BooleanFormula bEq3 = rmgr.equal(b, rmgr.makeNumber(3));
                BooleanFormula implication1 = bfmr.implication(aEq0, bEq2);
                BooleanFormula implication2 = bfmr.implication(aEq0, bEq3);
                BooleanFormula constraint = bfmr.and(implication1, implication2);
                prover.push();
                System.out.println("Here1");
                prover.addConstraint(constraint);
                boolean isUnsat = prover.isUnsat();
                prover.pop();

                prover.push();
                System.out.println("Here2");
                prover.addConstraint(constraint);
                System.out.println("Here3");
                boolean isUnsat2 = prover.isUnsat();

                if (isUnsat) {
                    System.out.println("UNSAT");
                } else {
                    System.out.println("SAT");
                }
                prover.pop();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (SolverException e) {
                e.printStackTrace();
            }
        } catch (InvalidConfigurationException e) {
            e.printStackTrace();
        }
    }
```

If I change the prover option to GENERATE_MODELS, everything works fine. Somehow, the BooleanFormula **constraint** gets polluted after the first check-sat.

**Comment by kfriedberger** [comment]
Hi @baoluomeng ,
thanks for reporting this issue. Your Java example is very good and simplifies debugging. I could already reproduce this problem on my system (Linux64) with several versions of Z3 in JavaSMT. It looks like an issue in JavaSMT, so I look for a solution.
Best,
Karlheinz

**Comment by baoluomeng** [comment]
Thank you @kfriedberger for the quick fix. 
We are actively using this feature in our project. So I am wondering when you are planning to make the next release? Or is there any Maven dev release I can use in our project?

**Comment by kfriedberger** [comment]
We do not provide Maven-Snapshots. I will provide a new release version soon.
