### ISSUE TITLE
Possible bad index in Native.getAppArg for Z3_OP_FPA_TO_FP

### ISSUE THREAD

**Issue by leventeBajczi** [sosy-lab/java-smt#359]
In the following line: 

https://github.com/sosy-lab/java-smt/blob/9b7ff83501247b15334ce29308637dc68fff3253/src/org/sosy_lab/java_smt/solvers/z3/Z3FormulaCreator.java#L741C36-L742C95

The first argument of the `to_fp` function is queried, causing (in my case) a `com.microsoft.z3.Z3Exception: index out of bounds` exception. 

The problem arises while using a FormulaVisitor to visit the term created by the following code:

``` Java
      final Configuration config = Configuration.fromCmdLineArguments(new String[]{});
      final LogManager logger = BasicLogManager.create(config);
      final ShutdownManager shutdownManager = ShutdownManager.create();
      final SolverContext context = SolverContextFactory.createSolverContext(config, logger, shutdownManager.getNotifier(), Solvers.Z3);

      final Formula term = context.getFormulaManager().getFloatingPointFormulaManager().fromIeeeBitvector(
              context.getFormulaManager().getBitvectorFormulaManager().makeBitvector(16, BigInteger.ZERO),
              FormulaType.getFloatingPointType(5, 10)
      );

      context.getFormulaManager().visit(term, new DefaultFormulaVisitor<Void>() {
          @Override
          protected Void visitDefault(Formula f) {
              return null;
          }
      });

```

I think this is supposed to be 0, but given the lack of documentation I could find about the Native.getAppArg function, I'm not confident about this decision.

**Comment by kfriedberger** [comment]
Thanks for reporting. I can reprduce the problem. This is  bug in JavaSMT. I will provide a fix soon.
