### ISSUE TITLE
Packaging and Releasing

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#36]
That's what people mostly use.

**Comment by cheshire** [comment]
@PhilippWendler Any objections? :) I think we're good to go with 0.3 release.

**Comment by PhilippWendler** [comment]
Sure, why not?

**Comment by cheshire** [comment]
Apparently adding binaries to Maven Central is painful, and people use all kinds of hacks like packing them in binaries. Also of course one can't fetch Ivy packages with Maven, because that would make just too much sense for Java enterprise world.

**Comment by cheshire** [comment]
Setting up Maven central integration just for "common" took a better part of the weekend.
These things are ludicrously complicated and not very user friendly (good luck debugging an error message which just says "error code 400").
So now I'm not sure spending all the effort to put all the SMT solvers we have into Maven Central (there are at least two steps requiring manual validation on Maven Central side) is worth it + there is a difficult subject of who should release and maintain JARs for solvers we rely on.

On a downside, projects running Maven can not download dependencies from the Ivy repositories.

Any other release options? Currently, a user can manually recursively follow the dependencies from the .ivy file. That is quite annoying.
Maybe we should have a task to generate a .zip file containing all the dependencies for some sensible minimal release?

**Comment by cheshire** [comment]
Pushed to Maven central, but for now it's a very sad release with no bundled solvers.
