### ISSUE TITLE
Enable Simplify API for Bitwuzla

### ISSUE THREAD

**Issue by baierd** [sosy-lab/java-smt#373]
Bitwuzla supports simplification of formulas via the `simplify()` call. We should enable this in our wrapper for the next update of Bitwuzla.

**Comment by daniel-raffler** [comment]
I've opened a new branch and removed `simplify()` from the ignore list. We still need to decide when to call this method. According to the API documentation:

> Each call to [Bitwuzla::check_sat()](https://bitwuzla.github.io/docs/cpp/classes/bitwuzla.html#classbitwuzla_1_1Bitwuzla_1ad431abeb9f20944a08be8f94b14f81e8) simplifies the input formula as a preprocessing step. It is not necessary to call this function explicitly in the general case.

However, there may still be some exceptions?
