### ISSUE TITLE
SIGFPE from FloatingPointFormulaManager::makeNumber() with numbers <1e-03 (Z3)

### ISSUE THREAD

**Issue by jasper-vb** [sosy-lab/java-smt#388]
I'm using java-smt 5.0.0 with javasmt-solver-z3 4.12.5 on Ubuntu 22.04 (via WSL). When I run the following MWE, the JVM crashes with a SIGFPE:

```java
package com.example.javasmt_sigfpe_mwe;

import org.sosy_lab.common.configuration.InvalidConfigurationException;
import org.sosy_lab.java_smt.SolverContextFactory;
import org.sosy_lab.java_smt.SolverContextFactory.Solvers;
import org.sosy_lab.java_smt.api.FormulaType;

class Main {
    public static void main(String[] args) throws InvalidConfigurationException {
        var ctx = SolverContextFactory.createSolverContext(Solvers.Z3);
        var fmgr = ctx.getFormulaManager();
        var fpmgr = fmgr.getFloatingPointFormulaManager();

        var ft = FormulaType.getDoublePrecisionFloatingPointType();
        var v = 9.999e-04;
        fpmgr.makeNumber(v, ft);
    }
}
```

When I change `v` to 1e-03, the program no longer crashes. Smaller numbers also seem to cause a crash.

Error report: [hs_err_pid338401.log](https://github.com/user-attachments/files/16928509/hs_err_pid338401.log)

I'm not sure if this is a Z3 issue or a java-smt issue, but I previously used libz3java and could create smaller numbers via `ctx.mkFP()`, although I didn't do the rounding that `Z3FloatingPointFormulaManager::makeNumberAndRound()` appears to do. However since the crash occurs already during the `Native.mkNumeral()` call (before the rounding), I doubt that's the issue.

**Comment by kfriedberger** [comment]
Hi @jasper-vb .

I tried to reproduce your issue and could not cause any crash.
 
However, I noted that your log-file contains references to `/usr/lib/x86_64-linux-gnu/jni/libz3java.so` which might not be related to JavaSMT and its dependencies. Please make sure to use the requird libraries (i.e., dependencies from Maven or Ant/Ivy) in the correct versions.
