### ISSUE TITLE
More Utility Methods

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#4]
Currently some helpful methods for constructing formulas are only implemented in the `FormulaManagerView` classes in CPAchecker. These should be identified and maybe moved to JavaSMT, with an implementation in `basicimpl` such that solver packages do not need to implement them.

**Comment by cheshire** [comment]
Quite a few of those methods were moved; I am closing this for now, feel free to re-open with a more concrete request.
