### ISSUE TITLE
Fix interpolation with Z3

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#40]
Interpolation in JavaSMT using Z3 is broken and produces a lot of segmentation faults.

The code we have for calling Z3 also looks questionable.

One point is that we seem to call the wrong function: `compute_interpolant` is for solving and computing interpolants, whereas `get_interpolant` is for computing an interpolant from an existing proof, which [should be used for incremental usage of the solver](http://stackoverflow.com/a/29757001/396730). The latter is what the JavaSMT API offers: first calling `isUnsat` and then repeatedly `getInterpolant`. As far as I understand the current Z3 API this means we are now repeatedly solving the same formulas, once for each `getInterpolant` call. This is of course a massive performance overhead. `compute_interpolant` also creates a model that we don't need here.

The current parameters to `compute_interpolant` may also be problematic. I don't know what C code gets generated for the JNI wrapper, but it seems there is at least something that cannot be correct. We pass a pointer for the `interp` parameter, but this pointer needs to point to an `Z3_ast_vector` of the correct length (of number of expected interpolants). I cannot see how our code could create a vector of the correct length here. I think this might be the cause of the segfaults.
There is also no cleanup code here, for example the array and the returned model should be freed.

Additionally, I could not find any documentation for `compute_interpolant`. So I think before this gets redone, one should ask the Z3 developers for documentation and instructions on how to implement this properly. It is important to do this properly, because if we do this incorrectly, this might upset both our users and the Z3 developers.

**Comment by cheshire** [comment]
> Additionally, I could not find any documentation for compute_interpolant. 

Where are you normally looking for the documentation? I think the website you normally reference is severely outdated.
The docstrings in the header file in Z3 codebase are normally pretty good:

```c
    /* Compute an interpolant for an unsatisfiable conjunction of formulas.

       This takes as an argument an interpolation pattern as in
       #Z3_get_interpolant. This is a conjunction, some subformulas of
       which are marked with the "interp" operator (see #Z3_mk_interpolant).

       The conjunction is first checked for unsatisfiability. The result
       of this check is returned in the out parameter "status". If the result
       is unsat, an interpolant is computed from the refutation as in #Z3_get_interpolant
       and returned as a vector of formulas. Otherwise the return value is
       an empty formula.

       See #Z3_get_interpolant for a discussion of supported theories.

       The advantage of this function over #Z3_get_interpolant is that
       it is not necessary to create a suitable SMT solver and generate
       a proof. The disadvantage is that it is not possible to use the
       solver incrementally.

       Parameters:

       \param c logical context.
       \param pat an interpolation pattern
       \param p parameters for solver creation
       \param status returns the status of the sat check
       \param model returns model if satisfiable

       Return value: status of SAT check

       def_API('Z3_compute_interpolant', INT, (_in(CONTEXT), _in(AST), _in(PARAMS), _out(AST_VECTOR), _out(MODEL)))
       */

    Z3_lbool Z3_API Z3_compute_interpolant(Z3_context c,
                                           Z3_ast pat,
                                           Z3_params p,
                                           Z3_ast_vector *interp,
                                           Z3_model *model);

```

**Comment by PhilippWendler** [comment]
> Where are you normally looking for the documentation?

I looked at the [official documentation of the C API](https://z3prover.github.io/api/html/group__capi.html#ga0e4fcbcebd66c4f9f5043611f24338ef).

**Comment by cheshire** [comment]
Maybe there's a bug with the Doxygen generation procedure. Normally header files are better.

**Comment by cheshire** [comment]
@stieglma Given that the Z3 issue was closed, any suggestions what to do with this one?

**Comment by stieglma** [comment]
Well, with the ```-stack``` parameter for CPAchecker we have a workaround for not getting problems with stackoverflows in Z3, however I wouldn't consider this bug fixed, but as it is not on our side I think we could close this issue and just mention somewhere in the documentation that Z3 needs some extra parameters for working properly?

**Comment by PhilippWendler** [comment]
So are all segfaults gone if the stack size is increased appropriately? If yes, then this just needs to be documented and the issue can be closed. Otherwise, we need to investigate further.

**Comment by stieglma** [comment]
@kfriedberger did some tests for it, i think everything was ok with the increased stack size

**Comment by kfriedberger** [comment]
in my tests, the number of segfaults was reduced, 
but not all were gone, and there were some exceptions (which may not be related to the stacksize).

**Comment by stephanlukasczyk** [comment]
I can confirm these results. For the benchmark runs for my Bachelor's thesis, I got segfaults for about 300 of 5400 runs with Z3 (CPAchecker predicate analysis with uninterpreted functions), although I've set the stack size to 10M. A quick random check on two or three tasks with a stack size of 100M made the segfault disappear, but I can't say anything about the rest. If you want, I could re-run the set with a stack size of 100M and check whether the segfaults disappear.

**Comment by cheshire** [comment]
> this just needs to be documented and the issue can be closed

Any good advice on where to put the documentation?
It's not like we can catch a segfault and return an error message "consider increasing your stack size".

**Comment by stephanlukasczyk** [comment]
@kfriedberger Sorry, I didn't get any information about your like. Just for completion of this topic: I did the benchmark with the same configuration but 100M stack size again and got 166 instead of 318 segfaults. I've uploaded the [result table](http://students.fim.uni-passau.de/~lukasczy/results.2016-04-27_1541.table.html) and the [diff table](http://students.fim.uni-passau.de/~lukasczy/results.2016-04-27_1541.diff.html), if you are interested (remark: the CPAchecker and JavaSMT versions used are from mid of March).

**Comment by cheshire** [comment]
@stephanlukasczyk 

> I did the benchmark with the same configuration but 100M stack size again

Wow, even assuming that Java is heavier than C++, 100M is a lot.

> and got 166 instead of 318 segfaults

Can we get it to 0? Would we need 200M, 300M, 500M? :P :P

**Comment by stephanlukasczyk** [comment]
@cheshire I don't think this will help us, even with 1GB of stack. We might be able to again reduce the number of segfaults but also with my current results, about half of the tasks now time out instead of segfaulting.
If you really want, I can of course do the benchmarks again with 500M or even more, but I don't think this will solve the problem :)
