### ISSUE TITLE
Why does Princess need to export its logic "AUFLIA" when dumping formulas?

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#43]
No other solver seems to exports the used logic.
Why do we do this only and explicitly for Princess?
Perhaps this line should be removed:
https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/solver/princess/PrincessEnvironment.java#L260

Related:
In the JunitTest `TranslateFormulaTest`, the solver pair of Princess and SMTInterpol prints the output "unsupported" due to a miss-match in the dumped logic. Princess explicitly dumps the logic `AUFLIA`, while SMTInterpol does not support it, and thus prints "unsupported" while parsing. The formulas are parsed as expected, because the default logic (`QF_AUFLIRA`) is already set for SMTInterpol.

**Comment by cheshire** [comment]
Is there any reason for us to set the logic at all?

**Comment by kfriedberger** [comment]
Some solvers want to have a logic set at the beginning. 

Example SMTInterpol:
https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/solver/smtinterpol/SmtInterpolEnvironment.java#L145

We always set the most global logic for JavaSMT-solvers, i.e. that we have support for quantifiers, arrays and bitvectors together, if possible. Depending on the logic we can use pre-defined operators like PLUS, MINUS, LEQ, UFs and sorts like INT, BV, REAL.

Some solvers (Mathsat, Z3) use their most common logic by default.

However, this was not my question. I am asking **whether we should dump the logic** or not.

**Comment by cheshire** [comment]
I would prefer not to dump logic at all, unless we have a reliable solver-independent way to detect the "minimal" (? for some reasonable definition of minimal?) logic used.

**Comment by kfriedberger** [comment]
done. d18c04dc5db1e9997cc02e4e9e500d08910f92f5
