### ISSUE TITLE
Check and throw for unsupported ProverOptions

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#45]
The implementors of `SolverContext.newProverEnvironment(ProverOptions...)` should check whether the requested options contain only features that the current solver supports, and throw `UnsupportedOperationException` otherwise ([original request](https://github.com/sosy-lab/java-smt/commit/eeaaad65e863c1c7ad21a8a7b7442e74f6436139#commitcomment-15369709)).

It is better to fail early when the prover environment is created than late when the feature is actually used. Furthermore, this is a safe guard for when we add new values to the `ProverOptions` enum and forget to update some solvers.

This also needs to be documented, of course.

**Comment by cheshire** [comment]
This is a nice idea in principle, but in practice without adding AbstractProverEnvironment (or similar) across all solvers this would result in large code duplication.
Do you think adding `AbstractProverEnvironment` and extending everything from it is the way to go?

**Comment by PhilippWendler** [comment]
Well, I think this is not a nice idea, but strictly necessary for a good API. So if you think you need `AbstractProverEnvironment` for this, then add it. I think it is possible to implement this in the existing `AbstractSolverContext`.
