### ISSUE TITLE
Check AbstractFormulaManager.substituteUsingMapImpl()

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#46]
The method [AbstractFormulaManager.substituteUsingMapImpl()](https://github.com/sosy-lab/java-smt/blob/56d8b8b27fb993482827054f9c8905d84b06fc65/src/org/sosy_lab/solver/basicimpl/AbstractFormulaManager.java#L301) gets two parameters `expr` and `memoization` which are not used. This is quite suspicious and may be a bug because the single caller of this method does extra effort to create these parameters. Is the method buggy or should these paramaters be removed?

**Comment by cheshire** [comment]
Neither.

The user-facing API gives both wrapped and unwrapped versions to the caller.
Generic implementation uses wrapped versions. Solver-specific implementation uses unwrapped ones.

Do you think you could revert the TODO comment?

**Comment by PhilippWendler** [comment]
No, I will not to revert the TODO because the current code still needs improvement:

- There are no solver-specific implementations of this method, so why have both parameters?
- If we want to allow solver-specific implementations, there should be two methods, one for the wrapped formulas calling the other one for the unwrapped formulas, just like in all the other methods in the basicimpl package. Mixing both in one method is error-prone and hard to understand.
- Even if the current code would be kept, this absolutely needs to be very clearly documented, with a precise description of the meaning of each parameter, and the `@param` tag in the Javadoc would replace the `@SuppressWarnings("unused")`.

**Comment by cheshire** [comment]
I've added a solver-specific implementation for Z3, that was indeed a bug.
I have also added documentation.

With the current code structure I do not see how your second point can be implemented without significant complications.
