### ISSUE TITLE
Z3 segfault in is_numeral_ast

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#49]
In CPAchecker, there is a case where Z3 segfaults inside the `is_numeral_ast` function.

The full crash information including stack trace is available here: https://buildbot.sosy-lab.org/results/integration-policyIteration/3232.integration-policyIteration.diff.html

Not sure whether this is a bug in the JNI wrapper or in Z3 itself.

**Comment by kfriedberger** [comment]
Additional info:
The bug appears in combination with a timeout in CPAchecker.

**Comment by cheshire** [comment]
@PhilippWendler  @kfriedberger I think it has nothing to do with JavaSMT, Z3 just sometimes reacts with segfaults to interruptions.

**Comment by cheshire** [comment]
I've opened a bug in Z3 (https://github.com/Z3Prover/z3/issues/595#issuecomment-218451621), closing this one, as we can't do anything in JavaSMT.
