### ISSUE TITLE
Fail on unexpected types of model values

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#53]
If a value appears in a model with a type which we do not expect and that we do not know how to handle, the implementations for MathSAT5, SMTInterpol, and Z3 return the value's string representation. The implementation for Princess throws an IllegalArgumentException.

I suggest to make this behavior the same for all solvers, and to always throw an exception. By falling back to the string we hide bugs in the conversion logic, and we will not find all cases that we can and should handle. An exception is also more future-proof: if somebody relies on the string being returned it would be backwards-incompatible to change it to a better representation later on, whereas such a problem would not occur if the throw an exception now.

**Comment by PhilippWendler** [comment]
A similar case is in `Z3Model.evaluateImpl`: it returns `null` (which means "don't care") whenever it cannot convert the value. Not sure how the implementations for other solvers handle this.

**Comment by cheshire** [comment]
> A similar case is in Z3Model.evaluateImpl: it returns null (which means "don't care") whenever it cannot convert the value

That's actually meant to be a feature, as Z3 does not give us any other way to indicate that the answer is "don't care": it simply returns the input AST. I've had a ticket on Z3 about this a while ago.

**Comment by cheshire** [comment]
Other than that, can this be closed?

**Comment by PhilippWendler** [comment]
Ah, found https://github.com/Z3Prover/z3/issues/536.

So I think then we should check whether it is the input AST and treat it as "don't care", but still throw an exception for all other values.

**Comment by cheshire** [comment]
@PhilippWendler I think it's not that simple, as it might not be _exactly_ input AST (they replace part of it with constants or something? I forgot the details).
I think the current solution is the least of all evils.

**Comment by PhilippWendler** [comment]
Ouch, that's unfortunate. There should really be a comment at this place telling this reason.

Btw, at least `Z3FormulaCreator.convertValue` still has the unwanted behavior (returning string instead of throwing an exception). I did not check whether there are any other places left.
