### ISSUE TITLE
Princess model fails if UFs are applied to quantified variable

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#54]
Terms with quantified variables cannot be given to the model evaluator of Princess. If there is a UF in the asserted formulas which is applied to a quantified variable, this application term is collected by the TermExtractionVisitor and then evaluated, which fails. 506332553abeec03d17eb1678766883b58c2d095 adds a failing unit test for this.

**Comment by cheshire** [comment]
@PhilippWendler Actually I only got quantifiers reliably working for Z3. For Princess I get all kinds of different crashes: I think this is reflected in `assume` statements in unit tests.

**Comment by cheshire** [comment]
(this is not to say that this particular bug can not be fixed, I'm just saying what to expect in general)

**Comment by PhilippWendler** [comment]
Actually, the Princess class `PartialModel` has a mapping from terms to values which is available with `model.interpretation()`. Probably this can be used to replace the TermExtractionVisitor such that this problem would not occur.

**Comment by cheshire** [comment]
Ah great, I must have missed `PartialModel` somehow.

**Comment by PhilippWendler** [comment]
The crashes are gone now. The Princess model contains terms like `store(0, 91489, -1): 0` which I cannot understand, maybe remove these? Otherwise this ticket can be closed.

**Comment by kfriedberger** [comment]
`store(0, 91489, -1): 0` is the assignment for an array (with arrayId/memory-address `0`), where `-1` is inserted at position `91489`. We handle these cases since last commit, see 5861adaa88d0d289757c51f846dbe851ac48730d .
