### ISSUE TITLE
Simplify Princess package

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#55]
I suggest to merge `SymbolTrackingPrincessStack` into `PrincessAbstractProver`. The interface `PrincessStack` does not seem to be useful.

Maybe `PrincessEnvironment` can also be merged into `PrincessFormulaCreator`, `PrincessFormulaManager` and/or `PrincessSolverContext`.

**Comment by kfriedberger** [comment]
just for documentation:
`SymbolTrackingPrincessStack` was removed with 31989c5ecabcb9a5f7fe9ed782ef7536dc493718 .

**Comment by kfriedberger** [comment]
We will keep PrincessEnvironment as is, the same way as SMTInterpolEnvironment.
It serves as a wrapped around some central data-structures
that should not be accessible from other classes in this package.
