### ISSUE TITLE
API suggestion: swapping parameters for visiting and tactics

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#56]
@PhilippWendler @kfriedberger 

I wanted to ask first before doing changes.
I think I've chosen bad argument order for visitors: it's very annoying when the formula is a second argument, because it can be barely seen after often gigantic visitor class, and by the time the visitor class is written it's easy to forget that the formula has to be inserted as well.
Also it's impossible to just glance at the line and to see which formula the visitor is applied to.
Same goes for tactic application, albeit that's much less severe.

I think it's good to swap the order, and to do it while we can (pre 1.0).
Objections?

**Comment by PhilippWendler** [comment]
I agree.
