### ISSUE TITLE
Merge InterpolatingProverEnvironmentWithAssumptions into InterpolatingProverEnvironment

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#59]
The split between these two interfaces is now useless, because the only way to get an instance is via `SolverContext.newProverEnvironmentWithInterpolation()`, which returns `InterpolatingProverEnvironmentWithAssumptions`. It was only split because `InterpolatingProverEnvironmentWithAssumptions` was in CPAchecker when `InterpolatingProverEnvironment` was in JavaSMT.

**Comment by kfriedberger** [comment]
done with bf4e93a31f2706f1458095bf51af0be9b2343de9.
