### ISSUE TITLE
Make FormulaManagerFactory reusable

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#6]
`FormulaManagerFactory` currently gives out always the same solver instance. To simplify creation of multiple independent solver contexts, it should create a new one on every call. `getFormulaManager()` should be named something like `create()` then.

**Comment by cheshire** [comment]
Alternative API would be to add a static method to `FormulaManagerFactory` which would create a `FormulaManager`. I'll play around with various possibilities.

**Comment by cheshire** [comment]
I don't think it makes sense.
Normally you might want to tweak the `config` instance which is passed to the `FormulaManager`.
But that is not possible with the current API, as `FormulaManagerFactory` stores it.
I would be more in favor of making the constructor private and relying only on the static factory method.

**Comment by PhilippWendler** [comment]
I think it is good to be able to pass around `FormulaManagerFactory` instances if you need it. There may well be clients that wish to create multiple contexts with the same configuration.

It is trivial for us to support this, I see no reason to not do this.

Whether the constructor of `FormulaManagerFactory` is public or not is a different question, there can be a static method that gives out instances of the factory.

**Comment by cheshire** [comment]
This is a bit tricky. If each new call generates a new solver, how do we detect in `Solver` that we should use the same solver instance interpolation and solving?

The code which does transparent transfer-via-serialization between interpolation and solving contexts is in CPAchecker.

I think it makes more sense to migrate this option entirely from JavaSMT to CPAchecker (namely `Solver` class), as providing a separate solver for interpolation without transparent transfer does not make too much sense.

**Comment by PhilippWendler** [comment]
How is the feature of having different solvers for solving and interpolation related to the question of how `FormulaManagerFactory` works?

**Comment by cheshire** [comment]
It does. If `generateInterpolationContext()` always returns a new object, the caller has no way to check that two solvers are actually the same and use the same context.

**Comment by cheshire** [comment]
Thus this ticket is not possible without non-trivial API changes.

We can change `SolverContext` to encapsulate two contexts instead of one, like `Solver` does. 
Then `SeparateInterpolatingProverEnvironment` can be moved to JavaSMT as well.

Any other suggestions?

**Comment by PhilippWendler** [comment]
I understand now.

I agree that integrating `SeparateInterpolatingProverEnvironment` into JavaSMT would probably be the cleanest way to solve this.

**Comment by cheshire** [comment]
Would it?
If we do that, then `SolverContext` would be a bad name as it would encapsulate two contexts instead of one.

What if we just move selection of a second solver entirely to CPAchecker, and it would be up to CPAchecker to create a second solver context class?
Being able to use a second context specifically for interpolation seems somewhat CPAchecker-specific to me.

**Comment by cheshire** [comment]
https://github.com/sosy-lab/java-smt/commit/40689b28d0b677caf8c2a00e94efe7ae071751b3
