### ISSUE TITLE
Rethink package structure

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#60]
Currently, we have an `api` package, but not all of the API is inside it or in a subpackage. I would suggest to move the classes `SolverContextFactory` and `SolverException` as well as the package `visitors` into `api`.

If this is done, the package Javadoc of both the main package and the `api` package should be extended to give an overview over what is contained and what the relevant entry point is (this would be good anyway probably).

**Comment by cheshire** [comment]
If we don't move `SolverContextFactory` it's very obvious what is the entry point is, as it would be the only top-level class.
Then we don't have to document it as well.

As for the overview, I think the current Javadoc is quite good, what are you missing? More usage examples?

**Comment by PhilippWendler** [comment]
> If we don't move `SolverContextFactory` it's very obvious what is the entry point is, as it would be the only top-level class.

Yes. But then we have one class that is API but is not in `api`.

> As for the overview, I think the current Javadoc is quite good, what are you missing? More usage examples?

The package Javadoc is really short (just a few words). If you look at the Javadoc of JavaSMT, I believe you won't be able to understand where to start. The only sentence I found about this is from `doc/javadoc_overview.html`, which is only visible if you actually use the HTML pages (move it to `package-info.java`?). Of course there is the tutorial in the readme, but I always thought you are a fan of having as much as possible in the Javadoc :-).

So I would suggest a more detailed explanation about what are the relevant entry points of the package and how the classes are grouped together. E.g. for `api`: mention `SolverContext`, `Formula`, and `FormulaManager` explicitly, explain that for each theory there is a subinterface of `Formula` and a corresponding manager, etc.

**Comment by cheshire** [comment]
Actually I'm inclined to say "no" to the proposal about moving everything into the "api".
It's not very idiomatic, I don't see much benefit coming from it, and I really dislike making large b/w incompatible changes without a good reason.
@PhilippWendler are you going to make a stand over that?

I am in favor of adding more Javadoc, so I'll do that.

**Comment by PhilippWendler** [comment]
> Actually I'm inclined to say "no" to the proposal about moving everything into the "api".

Two classes and one small package is not that much as it sounds when you say "everything".

> It's not very idiomatic, I don't see much benefit coming from it, and I really dislike making large b/w incompatible changes without a good reason.
> @PhilippWendler are you going to make a stand over that?

No of course not. Though it is even less idiomatic if it does not contain all of the API. What if we rename it? Do you have suggestions? The only thing that comes to my mind except `api` is `core`.

Do you have another proposal do make the package structure clearer? Currently, the main package has this content:

- api: **relevant** for users
- basicimpl: only relevant for integrating own solvers
- logging: not relevant
- mathsat5: not relevant
- princess: not relevant
- smtinterpol: not relevant
- test: parts of it relevant for writing tests
- visitors: **relevant**
- z3: not relevant
- PackageSanityTest: not relevant
- SolverContextFactory: **relevant**
- SolverException: **relevant**

One could say this looks more like a random bunch of stuff than a consistent package hierarchy. Can we make it such that all the stuff that is relevant for users is basically in one place?

**Comment by cheshire** [comment]
> Two classes and one small package is not that much as it sounds when you say "everything".

It changes imports almost everywhere though, mainly due to `SolverException`.

IMO a much better change which I wanted to do for a long time would be to put all solver packages in a common package `solvers`.
We can also move `logging` to `basicimpl`.

Then I think it becomes obvious from the name what is relevant to users (everything except `basicimpl` and `*test`).
Even if `basicimpl` name could cause confusion, `package-info` inside should clear it.

**Comment by PhilippWendler** [comment]
> It changes imports almost everywhere though, mainly due to `SolverException`.

Yes, but I consider import changes not that bad (can be fixed with `sed`).

> IMO a much better change which I wanted to do for a long time would be to put all solver packages in a common package `solvers`.

This would also be a possibility (even in addition to moving the two classes). Maybe a different name to not end up with `org.sosy_lab.solver.solvers`?

> We can also move logging to `basicimpl`.

It does not really fit `basicimpl` because it is not used when implementing a solver wrapper.

**Comment by cheshire** [comment]
> Maybe a different name to not end up with org.sosy_lab.solver.solvers?

Yeah I was also thinking about this problem. `org.sosy_lab.solver.bindings`?

> Yes, but I consider import changes not that bad (can be fixed with sed).

Sure, yet still an annoyance.
I think moving bindings to different solvers would solve the problem of potentially confusing structure.

**Comment by PhilippWendler** [comment]
`bindings` is probably ok. What name is used by other libraries for this?

**Comment by cheshire** [comment]
@PhilippWendler e.g. PySMT uses solvers :P 
I currently want to push the name "backends". Objections?

**Comment by stieglma** [comment]
I like ```bindings``` more than ```backends``` but ```solvers``` is my favourite. When restructuring this, I would also suggest to rename the current ```solver``` package to ```javasmt```. Having the toolname in the package structure makes it much easier for users to find out which import comes from where. This change is also something that should (if it's done) be done before having the 1.0 release such that not too much is changing. I don't know how many projects are currently using JavaSMT but doing this renaming will hurt definitely less people when doing it earlier.
If we do such a big renaming changing the package of the exceptions shouldn't be a problem, too, as anyway every name will be changed.

**Comment by cheshire** [comment]
@stieglma OK if everyone likes your suggestion let's do that then.

**Comment by PhilippWendler** [comment]
@ottseb noticed that the `Tactic` enum is in the `basicimpl.tactics` package, although it is a public API (referenced by `FormulaManager.applyTactic`). I think it should be moved to `api`.

This raises the question where to put stuff like `UfElimination`. It is not a default implementation of one of our `Tactic`s, so `basicimpl.tactics` does not really fit. Furthermore, it is intended to be called by users, so it should not be below `basicimpl`. Maybe we add something like `java_smt.util`?

Another point to discuss is the `visitors` package. Parts of it are clearly API (`(Boolean)Formula(Transformation)Visitor` and `TraversalProcess`), so `api.visitors` seems appropriate. Other parts (like `Default*Visitor`) seem more like utilities.

**Comment by PhilippWendler** [comment]
`SolverContextStatistics` is also public API (referenced from `api`) but is in `basicimpl`. However, I think that these statistics are not ready to be part of a stable API yet.

**Comment by cheshire** [comment]
1. I'll move statistics to a branch.

> It is not a default implementation of one of our Tactics, so basicimpl.tactics does not really fit

I don't think so, I think that `UfElimination` is precisely a default implementation for one of the tactics, and should not be directly called by the users.

> Tactic enum is in the basicimpl.tactics package

OK, moved.

> Another point to discuss is the visitors package

I believe we are overthinking it, the aim was to gather API relevant for users in one location.
All of those classes, technically speaking, are API.
I think it makes much more sense to keep them as they are.

**Comment by cheshire** [comment]
Can I close this?

**Comment by PhilippWendler** [comment]
> I don't think so, I think that `UfElimination` is precisely a default implementation for one of the tactics, and should not be directly called by the users.

@ottseb knows best, but as far as I know it is *not* a tactic implementation because it does not match the signature of tactic application (it does not only return a formula but more than that).

>> Another point to discuss is the `visitors` package
> 
> I believe we are overthinking it, the aim was to gather API relevant for users in one location.
> All of those classes, technically speaking, are API.

So move all of them to `api.visitors`?

**Comment by ottseb** [comment]
Yes, it returns more than only the formula. The default implementation of tactic `ACKERMANNIZATION` uses `UfElimination`.

**Comment by cheshire** [comment]
> Yes, it returns more than only the formula. The default implementation of tactic ACKERMANNIZATION uses UfElimination.

Hm, OK, I think in a sense that violates the idea that everything is accessible through one single entry point (`SolverManagerFactory`). Maybe add utility methods like that to `FormulaManager`? (or group them in a separate manager, if we get many).

> So move all of them to api.visitors?

OK, I suppose. Changing all imports would be annoying.

**Comment by cheshire** [comment]
@ottseb So are you OK with the move I have suggested ?

**Comment by ottseb** [comment]
Would you hide `UfElimination` completely or would you just make the constructor package private and let `FormulaManager` create fresh instances of `UfElimination`?

**Comment by cheshire** [comment]
I want to expose `eliminateUfs` from the `FormulaManager`.
Ideally `UfElimination` class should not be accessible by the user, but I don't particularly care if we can't enforce it (we just conceptually would not treat it as public API).

**Comment by cheshire** [comment]
The `Result` class becomes public API then though.
In that case, do you want to rename it to `UfEliminationResult`, add public getters and move to `api`?
It's not very useful to give an object back to the user which does not have any public methods.

**Comment by ottseb** [comment]
Yes, I will do this.
There are public getters for the formula, the constraints and the substitution. What are you missing?

**Comment by cheshire** [comment]
@ottseb Ooops sorry did not see them.
OK thanks!
After that I believe that ticket can be closed.

**Comment by cheshire** [comment]
OK and now we should be done.
