### ISSUE TITLE
Discuss QuantifiedFormulaManager methods

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#62]
The methods `exist` and `forall` exist twice in `QuantifiedFormulaManager`, once with a list of variables and once with a varargs array of variables. The confusing thing is that the argument order is swapped between the two overloads. Of course the varargs method cannot have the variables first, but because "variable first" is supposedly the natural order for a quantifier method and because of the mismatch, I suggest dropping the varargs overloads. For the existing callers, I do not think that using the varargs method makes the caller code easier to read, on the contrary, the variable at the end is sometimes easily overlooked. Most of the existing callers did not even bother with the varargs method but call the list method, even if there is only one variable.

As an alternative one could add a method `exists(Formula variable, BooleanFormula body)` if the cost of writing `ImmutableList.of()` is considered too high.

**Comment by cheshire** [comment]
OK let's replace varargs with a single-argument method, I agree that swapping order is counter-intuitive.
