### ISSUE TITLE
Add possibility to specify floating-point rounding mode

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#63]
In order to fully use the floating-point theory, one needs to be able to specify the rounding mode for most arithmetic operations. Both MathSAT5 and Z3 support this, but the JavaSMT API does not export this. Instead we currently hard-code a specific rounding mode. This limits the usefulness of the current API.

I see two possible choices:
- Add a rounding-mode parameter to every method that needs it.
- Keep the existing methods, add a method `setDefaultRoundingMode`, and add an overload for every method with an additional rounding mode parameter. The current methods would delegate to the new ones and use the current default rounding mode.

If we decide to use the first one, we need to do this before release 1.0 or clearly mark the floating-point support as beta. From the perspective of CPAchecker both would be ok. If the first one is chosen, CPAchecker would probably implement the second one internally in its own JavaSMT wrapper.

**Comment by cheshire** [comment]
> Add a rounding-mode parameter to every method that needs it.

Are all those methods in FloatingPointFormulaManager?
I think we would need two methods: without the rounding mode (applying the default, supplied as a parameter), and with one, supplied as an argument.

**Comment by cheshire** [comment]
I think using parameters is a better idea than having a global setter, and implicit long-living global state.
