### ISSUE TITLE
Add Ackermannization tactic

### ISSUE THREAD

**Issue by ottseb** [sosy-lab/java-smt#66]
Ackermannization replaces UFs by fresh variables and adds constraints to enforce the functional consistency.

There should be a generic implementation for all solvers that does not have build in support. It would be useful if it is accessible as utility method that provides the substitution done during the transformation.

**Comment by cheshire** [comment]
@ottseb  Please take a look at the comments to the commit.

**Comment by ottseb** [comment]
Ackermannization of quantified formulas seems to be a very complex task. Therefore I would suggest to explicitly not support it until someone has an actual use case.

**Comment by cheshire** [comment]
@ottseb yeah sure, we just need to choose one approach and document it.
Possible options are:

 - Clean crash
 - Remove quantifiers beforehand
 - Leave UFs with quantified arguments alone.

We probably even want to support parameterized tactics, such that the choice can be made by the user. In this case, I think that any choice should be fine, provided it's tested and documented.

**Comment by cheshire** [comment]
@ottseb I assume this can be closed?
