### ISSUE TITLE
Global declarations with SMTInterpol

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#69]
JavaSMT uses "global" declarations (i.e., after the command sequence `push` - `declare-fun` - `pop`, the declared symbol is still valid). SMTInterpol did not support this so far, but once https://github.com/ultimate-pa/smtinterpol/pull/23 is merged, it seems to support this. JavaSMT should then make use of this feature for consistency with other solvers.

**Comment by cheshire** [comment]
@PhilippWendler Could you clarify what this be done? Perhaps I'm spoiled by working with Z3 too much, there there's no "declaration" API command, you just create a new symbol each time, and it uses the previous one if it already exists.

**Comment by kfriedberger** [comment]
We currently track symbols manually in JavaSMT and re-create them after each call of `pop`. We could remove a lot of code, if SMTInterpol support `global declarations`. I will take care of this.

**Comment by kfriedberger** [comment]
Hm, I cannot find the corresponding code in SMTInterpolEnvironment. Was it already simplified some time ago? Perhaps I am wrong here.

**Comment by PhilippWendler** [comment]
I vaguely remember problems with the old code and its removal. Maybe @stieglma knows more? I am not sure what the current state is, maybe there is code that actively checks for declarations on deeper stack levels or something else which would need to be removed. In any case, we probably need to enable global declarations in SMTInterpol explicitly and I think re-enable some of our tests that are disabled for SMTInterpol.
