### ISSUE TITLE
ProverEnvironment.allSat: Get the full assignment for each model

### ISSUE THREAD

**Issue by stahlbauer** [sosy-lab/java-smt#71]
Whenever a formula is SAT, the method *BasicProverEnvironment.getModel()* can provide assignments for the SMT (that is, including theories) variables found in the checked formula. 

It would be nice to get this assignments also for AllSAT-Calls (efficiently). The method *apply* of the interface *ProverEnvironment.AllSatCallback* could be extended such that the full model would be accessible.

**Comment by stahlbauer** [comment]
Whenever a formula is SAT, the method *BasicProverEnvironment.getModelAssignments()* can provide assignments for the SMT (that is, including theories) variables found in the checked formula. 

It would be nice to get this assignments also for AllSAT-Calls (efficiently). The method *apply* of the interface *ProverEnvironment.AllSatCallback* could be extended such that the assignment would be accessible.

**Comment by cheshire** [comment]
@stahlbauer Apart from SMTInterpol and MathSAT, `allSAT` is syntax sugar in JavaSMT.
Thus `getModel` can be called as normal.
It makes a lot of sense to disable model generation during allSAT, as for something that costly all operations should be rather fast.
Thus,

1) Are you sure you need a model? If you care about boolean terms only, maybe a predicate would suffice?
2) If you do need a model, I think you'll be better of writing allSat yourself, it's just a few lines of code.
Just use `ProverEnvironment#isUnsat` and assumptions (or even just push/pop).
