### ISSUE TITLE
Update Z3

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#72]
Z3 should be updated to a current version. The version introduced in f3f8d56, however, [segfaults](https://github.com/sosy-lab/java-smt/files/390584/hs_err_pid361.txt) when contexts are closed. This needs to be investigated and potentially a Z3 issue needs to be raised.

**Comment by cheshire** [comment]
Indeed looks like a bug in Z3.
I'll open a ticket, but I don't think it should block the 1.0 release, as it doesn't imply backwards incompatible API.
