### ISSUE TITLE
Ensure trivial automatic formula simplifications for all solvers

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#73]
Most solvers immediately simplify formulas when they are created, for example they remove trivial and duplicate operands of `and` and `or`, and flatten `and` and `or` if possible. These optimizations are cheap because they only affect the current operator and its operand, not the whole formula (in contrast to the `simplify` operation we provide). Altogether, these optimizations can still reduce the formula size significantly. Maybe this does not increase solving performance, but at the very least it makes formulas easier to read when they are dumped, e.g., for debugging. Thus I suggest to add implement such simplifications for solvers that do not do them automatically, i.e., Z3.

**Comment by cheshire** [comment]
@PhilippWendler E.g. check both operands and shortcut on `true`/`false` for `and` and `or` functions? Wouldn't it make much more sense to do that in Z3?

**Comment by PhilippWendler** [comment]
Yes, and the same for n-ary operations, too. If operands contain duplicate entries, these can be removed, too.

Z3 could do so itself, like our other solvers do, but I am not sure whether they want to (one could assume they would have done this a long time ago if they wanted).

**Comment by cheshire** [comment]
I have opened Z3 ticket, if they'll close it, I'll do it in JavaSMT.

**Comment by cheshire** [comment]
@PhilippWendler OK I'll do it, do we want any other trivial simplifications (multiplication by zero, multiplication by one, adding zero?...)

**Comment by PhilippWendler** [comment]
Maybe, yes. As long as checking is local (i.e., `O(n)` with `n` being the number of parameters of the current term) I guess it is acceptable performance-wise.

What other solvers also do is elimination of duplicate arguments to operators like `and` and `or`. This can also be done in `O(n)` by traversing over the arguments and copying them into a new list or array, keeping a HashSet of "already seen" arguments.

**Comment by cheshire** [comment]
Interesting, I suspect that with hash consing we do not even need to do
equality testing on AST objects, as the returned native pointers would be
identical.

**Comment by cheshire** [comment]
@PhilippWendler Do you think hould we have an optional checking (controlled by a flag), or just always-enabled? I think I would be in favor of a flag.

**Comment by PhilippWendler** [comment]
I would do this always. Why would anyone want to turn this off? For other solvers it is also always on, and we can't change it.

**Comment by kfriedberger** [comment]
Some simplification was done in fd6dc1de0ef6d2d32e620af871c50e12c81f07f1, 0c9fe6f7020cff801b54263dc64a60a7c5033b3c, 36e47b5beb8e67938bf627367fd854a97a8e43f3
Any further proposals?

**Comment by cheshire** [comment]
> Any further proposals?

Apparently not anymore. Seems to be done.
