### ISSUE TITLE
Discuss GLIBCXX_3.4.20 dependency of MathSAT 5.3.12

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#75]
The new version 5.3.12 of MathSAT contains a reference to the symbol `std::__throw_out_of_range_fmt` (mangled to C symbol names, this is `_ZSt24__throw_out_of_range_fmtPKcz`). This symbol is available only from GLIBCXX_3.4.20 (shipped with GCC 4.9 or newer), which means that it is missing on e.g. Ubuntu 14.04 (which has only GCC 4.8).

I see the following alternatives:

1. We could ask the MathSAT developers to rebuild MathSAT with GCC <= 4.8 (and keep doing so in the future for several years).
1. We could try to find a workaround by supplying the symbol ourselves like we do for `memcpy`.
1. We could try to link the `libstdc++` statically into our MathSAT binary. This would mean that the library size increases and we could only build MathSAT on machines with a new GCC, but run it on older machines as well. Hopefully no other problems arise with this.

**Comment by PhilippWendler** [comment]
If we want to link `libstdc++` statically, here is some information on it. [1](http://www.trilithium.com/johan/2005/06/static-libstdc/) [2](http://stackoverflow.com/a/14082540/396730) [3](http://micro.nicholaswilson.me.uk/post/31855915892/rules-of-static-linking-libstdc-libc-libgcc).

Probably it would also be a good idea to hide all `libstdc++` symbols from our binary, as described in [this post](http://stackoverflow.com/a/452955/396730) with a linker script like the following:
```
MATHSATJ {
  global: Java_*;
  local: *;
};
```

Maybe this trick is also worthwhile anyway to hide the GMP symbols from being exported?

**Comment by cheshire** [comment]
I take it the relevant use case is the HPC cluster we have? I don't think that with new Ubuntu LTS released 14.04 is relevant.

**Comment by PhilippWendler** [comment]
I consider Ubuntu 14.04 as relevant, I am still using it myself. Not everybody updates their system immediately. Ubuntu 14.04 has official support from Canonical for another 3 years.

**Comment by cheshire** [comment]
OK, perhaps you're right, especially with glacial update times on student workstations.
Of the options you outlined I think only (3) is feasible. Do you remember on top of your head how much extra space are we talking about?

**Comment by PhilippWendler** [comment]
It is 1.5 MB of additional code.

**Comment by cheshire** [comment]
@PhilippWendler OK let's do this. I'll try to get around to this before the VSTTE camera-ready deadline, but any volunteering before that would be appreciated :P
