### ISSUE TITLE
Update GMP for MathSAT

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#81]
Currently, we link MathSAT against a pretty old version of [GMP](http://www.gmplib.org). This is done because we had problems updating to newer versions: the compiled binaries did not work on CPUs older than the one of the compiling machine because of incompatible machine operations.

We should update GMP to benefit from its fixes and (hopefully) performance improvements. In order to avoid the incompatible binaries, we should specify a target machine architecture for the configure script. I do not know, however, what is the best compromise between hardware compatibility and performance due to usage of CPU features.

**Comment by PhilippWendler** [comment]
According to the documentation, we could use `configure --enable-fat` to build a binary with optimized code for a range of x86 CPUs. Not sure if we still need to specify a minimum CPU architecture.

**Comment by cheshire** [comment]
Can we drop GMP binaries in the repo then?

**Comment by PhilippWendler** [comment]
Probably yes (there is no strict requirement to have them right now, it is just convenience for people building MathSAT).

**Comment by cheshire** [comment]
I've pushed the new version, linked against GMP6.1.1. It seems to work on Travis.
What other machines should I test it against and how? Run some CPAchecker integration test?

**Comment by PhilippWendler** [comment]
As many different CPUs as possible would be good, especially older ones. The Xeon E7-4870 and the Opteron 6380 in the VerifierCloud should be a good start.

How did you configure GMP?

**Comment by cheshire** [comment]
@PhilippWendler Same options as before, and `--enable-fat`.

I have tried `integration-predicateAnalysis` with `solver.solver=MATHSAT5` and CPU `6380`, seems to work. `2400` and `2650` work as well, and I don't think there is Xeon E7-4870 in the vcloud.
Seems good enough for me.

**Comment by PhilippWendler** [comment]
Nice. The E7 Xeons are sometimes there and sometimes not.

Btw, MathSAT 5.3.13 works mostly fine (a lot better than MathSAT 5.3.12), but I was promised that a new MathSAT with more bug fixes will be released soon, so before we update MathSAT we can probably wait for the new release. That release should then have all bugs from my extensive tests fixed.
