### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#83]
The current readme is very long (mostly because of the installation and the quickstart guide), and hard to read because it misses a table-of-contents. GitHub does not support auto-generated table-of-contents in readme files, thus I suggest to move some of the parts out of this file.

Furthermore, the current structure is confusing, because everything which comes after the quickstart currently belongs to the quickstart section when looking at the heading levels.

Some documentation should be added on what configuration options are supported. The readme claims that there are many configuration options, but there is no documentation on how to find out which ones exist. The auto-generated documentation from the OptionsCollector should probably be included somehow.

**Comment by cheshire** [comment]
OK.
I think we should absolutely keep the following items on the front page:

 - One paragraph description
 - Installation instructions
 - Quickstart example showing off initializing the context and solving some constraint.

Everything else can be moved, currently that would be "features" and "known solver issues".

**Comment by PhilippWendler** [comment]
I would prefer

- One paragraph description
- Feature overview
- Small example
- Links
- Authors

The goal of the front page is to motivate readers into using JavaSMT, or at least into investing more time into finding out about it, instead of closing that browser tab immediately.
The feature overview is probably quite important for this.

Installation instructions and quickstart example can both contribute to this goal, if they show convincingly and succinctly that installing and/or using JavaSMT is easy. The question is, do they achieve this?
Installation consists of several variants, with the easy ones being restricted to specific use cases, and the other ones being quite complex and tedious (not really motivating).
A short sentence like "Installation is possible via Maven, Ivy, or manually, cf. this page for more information." is probably better.

The quickstart example is motivating, but I think it is too long (more than two browser screens for me), which could make it seem that it is more effort than it really is, for example because it shows useless cruft like imports and explains the dependencies of JavaSMT with more text than JavaSMT itself!

Maybe put a short excerpt of the example here, something like this:
```java
// Instantiate JavaSMT with SMTInterpol as backend (for dependencies cf. documentation)
try (SolverContext context = SolverContextFactory.createSolverContext(
        config, logger, shutdownNotifier, Solvers.SMTINTERPOL)) {
  IntegerFormulaManager imgr = context.getFormulaManager().getIntegerFormulaManager();

  // Create formula "a = b" with two integer variables
  IntegerFormula a = imgr.makeVariable("a");
  IntegerFormula b = imgr.makeVariable("b");
  BooleanFormula f = imgr.equal(a, b);

  // Solve formula, get model, and print variable assignment
  try (ProverEnvironment prover = context.newProverEnvironment(ProverOptions.GENERATE_MODELS)) {
    prover.addConstraint(f);
    boolean isUnsat = prover.isUnsat();
    assert !isUnsat;
    try (Model model = prover.getModel()) {
      System.out.printf("SAT with a = %s, b = %s", model.evaluate(a), model.evaluate(b));
    }
  }
}
```

The existing quickstart guide can then be extended into a real, working example program that users can copy-and-paste for playing around with it (which is not possible with the current presentation).

Btw, the existing quickstart guide has broken imports, and it does not give a good example because it fails to close the context and the model appropriately.

**Comment by Notes03** [comment]
I have created a new branch for this issue: https://github.com/sosy-lab/java-smt/tree/readme_and_docs

Can you provide me feedback for the new Readme/Documentation please?

For a table of contents (if needed) there is a semi-automated solution: https://github.com/ekalinin/github-markdown-toc
If you want to have a table of contents, we can create this via the tool.

**Comment by kfriedberger** [comment]
@Notes03 
There is a broken markdown for `ShutdownNotifier` in section `Multithreading Support` in REAMDME.md  . Could you create a PullRequest such that we can merge your changes easily.
