### ISSUE TITLE
Define and use a consistent naming schema for JavaSMT

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#89]
It is not clear to me how the name "JavaSMT" is written officially, and existing uses of the name differ in spelling.

Examples:
- The website uses **JavaSMT**.
- The paper uses **JavaSMT** (at least in its title).
- The GitHub project is named **java-smt**.
- The [Ivy artifacts](https://www.sosy-lab.org/ivy/org.sosy_lab/) are named **javasmt**.
- The main [Maven artifacts](https://search.maven.org/#search|ga|1|sosy_lab) is named **java-smt**, but solver artifacts use **javasmt**.
- The source code uses **java_smt** as package name, which would be consistent with **java-smt**.
- The [ivy module](https://github.com/sosy-lab/java-smt/blob/master/ivy.xml) refers to a website with **javasmt** in the URL (which btw. does not exist and the URL is also broken).
- Most of the documentation uses **JavaSMT** ([example](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/package-info.java#L22)), but there is [one case](https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/example/package-info.java#L2) where it uses **Java-SMT**.
- The mailing list is named **java-smt**-dev.

I think it is particularly bad that the Maven name differs from the Ivy name, and that the Maven artifacts are named inconsistently. I did not find any other spellings such as "Java SMT".

We basically need spellings for these different situations:
1. A nice one in text for humans (where names are typically capitalized).
2. A lowercase one for identifiers that are typically lowercase-only, such as URLs.
3. A valid lowercase Java identifier for the package name.
4. (A valid Java identifier for class/method names - currently not necessary.)

Ideally, 2. would be created from 1. by simply lowercasing everything, and 3. would be created from 2. by replacing `-` with `_` as it is common.

**Comment by PhilippWendler** [comment]
I see these possible naming schemata:

**JavaSMT / javasmt / javasmt**:
I like the name "JavaSMT" as official project name most, and this would keep all "secondary" kinds of names consistent with the main name.
Easy and no potential for confusion. Disadvantage: a large number of changes (and changing the package name now would be bad).

**JavaSMT / javasmt / java_smt**:
Somewhat inconsistent, but at least consistent everywhere except the package name.
Much less effort to implement that the above proposal (GitHub has redirects at least, and the Maven artifact is probably not used at lot yet).

**JavaSMT / java-smt / java_smt**:
Least amount of changes necessary, but inconsistent. It would probably be hard to ensure that the name "javasmt" would really stay unused and not appear again because people see "JavaSMT" and just use it in lowercase spelling, leading to further inconsistency.

**Java-SMT / java-smt / java_smt**:
Also not many changes necessary, mostly in documentation where it is easy to do.
However, the paper uses "JavaSMT" and it is probably too late to change it.
Also, I personally do not really like the spelling "Java-SMT", and if we ever would like to add a class or method with Java-SMT in its name this would get really ugly.


There is also the possibility to keep using the existing names as they are, and only adopt a consistent schema for *new* cases. This would be **JavaSMT / (javasmt|java-smt) / java_smt** with a statement which of the two spellings is prefered.
This has the disadvantage of keeping existing inconsistencies like Maven vs. Ivy.

**Comment by cheshire** [comment]
> The source code uses java_smt as package name, which would be consistent with java-smt.

That's actually not a problem: it's somewhat standard to replace a dash by an underscore, since we can't use dashes in the package name.

> The mailing list is named java-smt-dev.

Not that we use it..

> Disadvantage: a large number of changes (and changing the package name now would be bad).

Sorry, for me changing the package name now is unacceptable. We already had too many changes, and now we're past 1.0.0.

I would also prefer to use "JavaSMT" consistently everywhere, but I don't think it's possible anymore.

**Comment by PhilippWendler** [comment]
> > The source code uses java_smt as package name, which would be consistent with java-smt.
> 
> That's actually not a problem: it's somewhat standard to replace a dash by an underscore, since we can't use dashes in the package name.

Yes, I said that `java_smt` in a package name is consistent with `java-smt` otherwise.

>   >  Disadvantage: a large number of changes (and changing the package name now would be bad).
> 
> Sorry, for me changing the package name now is unacceptable. We already had too many changes, and now we're past 1.0.0.

I agree, but I wanted to list all options for completeness.

> I would also prefer to use "JavaSMT" consistently everywhere, but I don't think it's possible anymore.

So what do you suggest?

**Comment by cheshire** [comment]
> So what do you suggest?

Both Maven and package names are set in stone now.
Ivy migration could be possible, but quite painful, and I would prefer to avoid that as well.

As for the Github repository name, and the name in the documentation I do not particularly care, given that Github supports transparent redirects.

**Comment by PhilippWendler** [comment]
I think this should be decided and finished before release 2.0.

**Comment by cheshire** [comment]
Can we go with your option "JavaSMT / java-smt / java_smt" ? I'm not against renaming Ivy/Maven artifacts for a new release, but I'm not sure how much of a pain it would be for people to upgrade (e.g. not finding upgrades / getting confused with two names present / how easy it is to deprecate a name).
I would still prefer not to change the package name, as I don't think the benefits outweigh the cost (it would hurt all users, and e.g. simplifying interpolation API will only touch those using it --- and also simplify the code).

**Comment by PhilippWendler** [comment]
I think the artifact renaming is not a big problem. People need to change their dependency config anyway to specify the new version number. Because the Maven artifacts are named inconsistently and different from the Ivy artifacts, we should rename some of them anyway.

So probably the main question for deciding between **JavaSMT / javasmt / java_smt** and **JavaSMT / java-smt / java_smt** is whether `javasmt` or `java-smt` is a better name for the GitHub project. Note that GitHub has redirects for the project, though I am not sure whether they als exist for the GitHub pages where the JavaDoc is.

**Comment by kfriedberger** [comment]
Closing this issue, because discussion is over.
We will use the new naming scheme for future releases.
