### ISSUE TITLE
Z3Exception in Z3OptimizationProver.upper()

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#94]
`Z3OptimizationProver.upper()` can throw a `Z3Exception` when the `ShutdownNotifier` is used to interrupt the SMT solver:
```
Exception in thread "main" com.microsoft.z3.Z3Exception: canceled
	at com.microsoft.z3.Native.simplify(Native.java:3125)
	at org.sosy_lab.java_smt.solvers.z3.Z3OptimizationProver.replaceEpsilon(Z3OptimizationProver.java:170)
	at org.sosy_lab.java_smt.solvers.z3.Z3OptimizationProver.upper(Z3OptimizationProver.java:128)
```
([source](https://buildbot.sosy-lab.org/results/integration-policyIteration/4149.integration-policyIteration.diff.html))

This should not happen, interruptible operations should be declared as `throws InterruptedException` and throw such an exception.

**Comment by cheshire** [comment]
@PhilippWendler sure, that raises a number of questions though.

1) We do not actually know which Z3 methods can throw exceptions while being interrupted, apparently it's not only "expensive" ones (checking satisfiability, etc).
A safe assumptions seems to be "all of them", but that would require writing a lot of boiler plate code (it could be done though, and try/catch blocks have almost no performance impact).
An easier option is, of course, to add exceptions one by one, as encountered in the wild.
Yet that would introduce b/w incompatible changes on each such commit, which leads us to the second point.

2) Technically, this would be a b/w incompatible change. Personally, as I am very unhappy with the current interpolation API (cf. #93) I would use the chance to fix both issues.

**Comment by PhilippWendler** [comment]
How would you solve this problem by adding a lot of try/catch blocks? What kind of code would you put into the catch blocks?

Currently the only way I see to handle these exceptions is to propagate them as `InterruptedException`. However, this leads to an awkward API, because we force all users of many methods to prepare for handling `InterruptedException` (even if they do not use Z3). And all this for a "feature" (interrupting cheap methods) that we do not even need/want.

So my suggestion would be to ask the Z3 developers if they could make sure that only certain "expensive" methods honor interrupts (and provide a list of them), or if they could add an additional mechanism to interrupt only expensive methods (maybe even specifically per prover environment?).

**Comment by cheshire** [comment]
Ooops, should have taken a more careful look at the stack trace, sorry =(

```
Exception in thread "main" com.microsoft.z3.Z3Exception: canceled
	at com.microsoft.z3.Native.simplify(Native.java:3125)
	at org.sosy_lab.java_smt.solvers.z3.Z3OptimizationProver.replaceEpsilon(Z3OptimizationProver.java:170)
	at org.sosy_lab.java_smt.solvers.z3.Z3OptimizationProver.upper(Z3OptimizationProver.java:128)
```

Indeed, Z3 does only interrupt only certain expensive methods, as confirmed by a quick grep through the codebase. It's our old friend `simplify` again.

**Comment by cheshire** [comment]
As the underlying substitution call does not handle interruptions, I think it's best to omit `simplify` entirely, as it's too heavy anyway.

**Comment by cheshire** [comment]
Pending https://github.com/Z3Prover/z3/issues/911 resolution.
