### ISSUE TITLE
No possibility to create InterpolatingProverEnvironment without model generation

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#98]
`SolverContext.newProverEnvironment` allows to create prover environments that do not support model generation. `SolverContext.newProverEnvironmentWithInterpolation` does not provide this possibility. Should this be added for symmetry? If yes, this would probably mean that model generation in `InterpolatingProverEnvironment` would be disabled unless explicitly requested, but this breaks backwards compatibility.

**Comment by PhilippWendler** [comment]
If we do a backwards-incompatible release anyway, I suggest to change this method to work similar to `newProverEnvironment`.

**Comment by cheshire** [comment]
If we go with #109 it should also include the option for generating UNSAT cores.
This ticket makes less sense without #109, as then the user could request UNSAT core generation, but then he would not be able to get the actual UNSAT core.

**Comment by PhilippWendler** [comment]
A standard solution for solving this problem is to have multiple enums which implement some interfaces. Example are the `OpenOption` and `CopyOption` interfaces and the `LinkOption`, `StandardOpenOption`, `StandardCopyOption`, etc. enums in `java.nio.file`.

**Comment by kfriedberger** [comment]
partially implemented in 5d5f4fdc167700653063b438003a191a83ca5af0 .
Lets wait for further request before over-engineering this part.
